<?php
use Models\Utilities\User;

?>
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-2 fixed-start ms-2 bg-gradient-dark"
id="sidenav-main" style="display:none">
<div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
    aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0 text-center py-2" href="<?=$this->zfUrl('home');?>" target="_blank">
        <h3 class="text-white mb-0">Admin</h3>
        <!-- <img src="/assets/customer/images/logo.png" class="navbar-brand-img h-100" alt="main_logo" style="max-height:4rem"> -->
    </a>
</div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto h-auto" id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item mb-2 mt-0">
                <a data-bs-toggle="collapse" href="#ProfileNav" class="nav-link text-white"
                    aria-controls="ProfileNav" role="button" aria-expanded="false">
                    <img src="<?=User::getAvatarUser($authen)?>" class="avatar" alt="Avatar">
                    <span class="nav-link-text ms-2 ps-1">
                        <?= $authen->adm_fullname ?? '';?>
                    </span>
                </a>
                <div class="collapse" id="ProfileNav" style="">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="<?=$this->zfUrl('profile')?>">
                                <i class="material-icons-round opacity-10">manage_accounts</i>
                                <span class="sidenav-normal  ms-3  ps-1"><?=$this->translate('Tài khoản của tôi')?></span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="<?= $this->zfUrl('logout');?>">
                                <i class="material-icons-round opacity-10">logout</i>
                                <span class="sidenav-normal  ms-3  ps-1"> <?= $this->translate('Đăng xuất')?> </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <hr class="horizontal light mt-0">
            
            <?= $items; ?>  
        </ul>
    </div>
</aside>