<?php
    $languages = [
        'vi' => '/assets/manager/images/vietnam-flag.png',
        'en' => '/assets/manager/images/USA-flag.png',
    ]
?>
<nav class="navbar navbar-main navbar-expand-lg position-sticky mt-1 top-1 px-0 mx-2 shadow-none border-radius-xl z-index-sticky"
    id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">
        <div class="sidenav-toggler sidenav-toggler-inner d-xl-block d-none ">
            <a href="javascript:void(0);" class="nav-link text-body p-0">
                <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                </div>
            </a>
        </div>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                <a type="button" class="btn btn-outline-primary btn-sm mb-0" 
                    target="_blank" href="<?= $this->zfUrl('home') ?>">
                    <?= $this->translate('Website') ?>
                </a>
            </div>
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item dropdown px-3">
                    <a href="javascript:void(0);" class="nav-link text-body p-0 position-relative" id="languageDropdown"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="<?=$languages[APPLICATION_LANGUAGE]?>" alt="Vietnam Flag" width="22" height="22" 
                            style="margin-top:-4px" class="me-1">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end p-2 me-sm-n4" aria-labelledby="languageDropdown">
                        <li class="mb-2">
                            <a class="dropdown-item" href="/">
                                <img src="/assets/manager/images/vietnam-flag.png" alt="Vietnam Flag" width="22" height="22" 
                                    style="margin-top:-4px" class="me-1">
                                <?=$this->translate('Tiếng Việt')?>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a class="dropdown-item" href="/en">
                                <img src="/assets/manager/images/USA-flag.png" alt="Vietnam Flag" width="22" height="22" 
                                    style="margin-top:-4px" class="me-1">
                                <?=$this->translate('English')?>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a href="javascript:void(0);" class="nav-link text-body p-0 position-relative" id="dropDownUser"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="material-icons me-sm-1">
                            account_circle
                        </i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end p-2 me-sm-n4" aria-labelledby="dropDownUser">
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="<?= $this->zfUrl('profile') ?>">
                                <div class="d-flex align-items-center py-1">
                                    <span class="material-icons">account_circle</span>
                                    <div class="ms-2">
                                        <h6 class="text-sm font-weight-normal my-auto">
                                            <?= $this->translate('Tài khoản của tôi'); ?>
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="<?= $this->zfUrl('logout') ?>">
                                <div class="d-flex align-items-center py-1">
                                    <span class="material-icons">logout</span>
                                    <div class="ms-2">
                                        <h6 class="text-sm font-weight-normal my-auto">
                                            <?= $this->translate('Đăng xuất') ?>
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:void(0);" class="nav-link text-body p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </a>
                </li>
                <li class="nav-item px-3">
                    <a href="javascript:void(0);" class="nav-link text-body p-0">
                        <i class="material-icons fixed-plugin-button-nav cursor-pointer">
                            settings
                        </i>
                    </a>
                </li>
                <li class="nav-item dropdown pe-2">
                    <a href="javascript:void(0);" class="nav-link text-body p-0 position-relative"
                        id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="material-icons cursor-pointer">
                            notifications
                        </i>
                        <span
                            class="position-absolute top-5 start-100 translate-middle badge rounded-pill bg-danger border border-white small py-1 px-2">
                            <span class="small">11</span>
                            <span class="visually-hidden">unread notifications</span>
                        </span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end p-2 me-sm-n4" aria-labelledby="dropdownMenuButton">
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="javascript:void(0);">
                                <div class="d-flex align-items-center py-1">
                                    <span class="material-icons">email</span>
                                    <div class="ms-2">
                                        <h6 class="text-sm font-weight-normal my-auto">
                                            Check new messages
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="javascript:void(0);">
                                <div class="d-flex align-items-center py-1">
                                    <span class="material-icons">podcasts</span>
                                    <div class="ms-2">
                                        <h6 class="text-sm font-weight-normal my-auto">
                                            Manage podcast session
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item border-radius-md" href="javascript:void(0);">
                                <div class="d-flex align-items-center py-1">
                                    <span class="material-icons">shopping_cart</span>
                                    <div class="ms-2">
                                        <h6 class="text-sm font-weight-normal my-auto">
                                            Payment successfully completed
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>