
<nav class="navbar navbar-expand-lg card mb-2 mt-2 px-0 border-radius-xl nav-toolbar"
style="display:none">
    <div class="container-fluid py-1 px-3">
        <div aria-label="breadcrumb">
            <?php echo $this->pageBreadcrumbs()->render(); ?>
        </div>

        <a href="javascript:;" class="nav-link d-lg-none text-body p-0 btn-toolbar" data-bs-toggle="collapse" 
            data-bs-target="#navToolbar" aria-controls="navToolbar" aria-expanded="false">
            <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
            </div>
        </a>
		<?php echo $this->bootstrapToolbar()->toString(); ?>
    </div>
</nav>

    		