<div class="card mt-4" id="password">
    <div class="card-header">
        <h5>
            <?= $this->translate('Đổi mật khẩu') ?>
        </h5>
    </div>
    <div class="card-body pt-0">
        <div class="input-group input-group-outline">
            <label class="form-label">
                <?= $this->translate('Mật khẩu hiện tại') ?>
            </label>
            <input type="password" name="old_password" id="old_password" class="form-control" autocomplete="off">
            <a href="javascript:;" class="position-absolute top-10px end-1 visible-icon show-pass" id="show-current-pass">
                <i class="material-icons" aria-hidden="true">
                    visibility
                </i>
            </a>
        </div>
        <div class="input-group input-group-outline my-4">
            <label class="form-label">
                <?= $this->translate('Mật khẩu mới') ?>
            </label>
            <input type="password" name="new_password" id="new_password" class="form-control" autocomplete="off">
            <a href="javascript:;" class="position-absolute top-10px end-1 visible-icon show-pass" id="show-new-pass">
                <i class="material-icons" aria-hidden="true">
                    visibility
                </i>
            </a>
        </div>
        <div class="input-group input-group-outline">
            <label class="form-label">
                <?= $this->translate('Xác nhận mật khẩu mới') ?>
            </label>
            <input type="password" name="confirm_new_password" id="confirm_new_password" class="form-control" autocomplete="off">
            <a href="javascript:;" class="position-absolute top-10px end-1 visible-icon show-pass" id="confirm-new-pass">
                <i class="material-icons" aria-hidden="true">
                    visibility
                </i>
            </a>
        </div>
        <h5 class="mt-5"><?= $this->translate('Yêu cầu mật khẩu')?></h5>
        <p class="text-muted mb-2">
            <?= $this->translate('Vui lòng làm theo hướng dẫn này để có mật khẩu mạnh:')?>
        </p>
        <ul class="text-muted ps-4 mb-0 float-start">
            <li>
                <span class="text-sm"><?= $this->translate('Phải bao gồm chữ cái in hoa, chữ thường, số, và ký tự đặc biệt.')?></span>
            </li>
            <li>
                <span class="text-sm"><?= $this->translate('Độ dài phải từ 6 đến 50 ký tự.')?></span>
            </li>
            <li>
                <span class="text-sm"><?= $this->translate('Thay đổi thường xuyên')?></span>
            </li>
        </ul>
        <a href="javascript:void(0);" id="btnChangePass"
            title="<?=$this->translate('Đổi mật khẩu')?>"
            class="btn bg-gradient-dark btn-sm float-end mb-0 mt-6">
            <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
            <span class="txt-btn"><?= $this->translate('Đổi mật khẩu') ?></span>
        </a>
    </div>
</div>
