<?php
use Laminas\Form\Element;

$this->headTitle($this->translate($pageTitle));
$this->menuLeft()->setActiveItemId($activeItemId);

$breadCrumb = [
    $this->translate('Home') => $this->zfUrl('home')
]; 
if ($parentEntity)
    $breadCrumb[$this->translate('Prefecture category')] = $this->zfUrl(
        $routeName, ['action' => 'small', 'id' => $parentEntity->ga_id ?? '']
    );
else 
    $breadCrumb[$this->translate('Regional category')] = $this->zfUrl($routeName);
$breadCrumb[$pageTitle] = '#';
$this->pageBreadcrumbs()->setItems($breadCrumb);

$this->bootstrapToolbar([
    $this->toolbarSaveAndClose(),
    $this->toolbarClose(
        $this->zfUrl(null, [], ['useOldQuery' => true])
    )
]);
?>

<div class="content__title">
    <h2>
        <?= $pageTitle ?>
    </h2>
</div>
<div class="card-body card-padding">
    <div class="row">
        <div class="col-md-6">
            <form method="post" name="adminForm" enctype="multipart/form-data" id="adminForm">
                <input type="hidden" id="adminAction" value="" name="adminAction">

                <div class="form-group">
                    <label for="title">
                        <?= $this->translate('Region title') ?>&nbsp;<span class="required">*</span>
                    </label>
                    <input type="text" id="title" name="title" class="form-control" maxlength="15"
                        placeholder="例：関東"
                        value="<?= $postVals['title'] ?? '' ?>">
                    <i class="form-group__bar"></i>
                </div>

                <div class="form-group">
                    <label for="name">
                        <?= $this->translate('Tab name') ?>&nbsp;<span class="required">*</span>
                    </label>
                    <input type="text" id="name" name="name" class="form-control" maxlength="15"
                        placeholder="例：kanto_tab"
                        value="<?= $postVals['name'] ?? '' ?>">
                    <i class="form-group__bar"></i>
                </div>

                <div class="form-group">
                    <label for="status">
                        <?= $this->translate('Availability') ?>
                    </label>
                    <div class="select">
                        <?php
                        $select = new Element\Select('status');
                        $select->setAttributes([
                            'class' => 'form-control',
                            'id' => 'status'
                        ]);
                        $select->setValueOptions([
                            '1' => $this->translate('Display'),
                            '0' => $this->translate('Hidden'),
                        ]);
                        $select->setValue($postVals['status'] ?? '');
                        echo $this->formSelect($select);
                        ?>
                        <i class="form-group__bar"></i>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>