<?php
use Laminas\Form\Element;

$this->headTitle($pageTitle);
$breadCrumb = [
    $this->translate('Home') => $this->zfUrl('home')
]; 

if ($parentEntity)
    $breadCrumb[$this->translate('Regional category')] = $this->zfUrl($routeName);
$breadCrumb[$pageTitle] = '#';
$this->pageBreadcrumbs()->setItems($breadCrumb);

$this->menuLeft()->setActiveItemId($activeItemId);

$toolbars = [
    $this->toolbarChangeOrder(
        $this->zfUrl(null, [
            'action' => 'change-order',
            'pid' => $parentEntity->ga_id ?? null
        ])
    ),
    $this->toolbarInsert(
        $this->zfUrl(null, [
            'action' => 'add',
            'pid' => $parentEntity->ga_id ?? null
        ])
    )
];

if (!empty($parentEntity)) {
    $toolbars[] = $this->toolbarClose();
    $this->headStyleAction('.cate-child{display: none}');
}
$this->bootstrapToolbar($toolbars);
?>
<div class="content__title">
    <h2><?= $pageTitle?></h2>
</div>

<div class="card">
    <div class="card-body">
        <form action="" method="get" name="filter-form" id="filter-form">
            <div class="row">
                <div class="col-sm-12 col-md-4 col-lg-4">
                    <div class="results__search">
                        <input type="text" class="search-field form-control" name="keyword" maxlength="50" id="keyword"
                            placeholder="<?= $this->translate('Keyword') ?>"
                            value="<?= htmlspecialchars($_GET['keyword'] ?? '') ?>">
                    </div>
                </div>
                <div class="visible-xs-block" style="height: 5px"></div>

                <div class="col-sm-12 col-md-4 col-lg-3">
                    <div class="form-group">
                        <div class="select">
                            <?php
                            $select = new Element\Select('status');
                            $select->setAttributes([
                                'class' => 'form-control',
                                'id' => 'status',
                            ]);
                            $select->setValueOptions([
                                '' => $this->translate('All State'),
                                '1' => $this->translate('Active'),
                                '0' => $this->translate('Inactive')
                            ]);

                            $select->setValue($_GET['status'] ?? '');
                            echo $this->formSelect($select);
                            ?>
                            <i class="form-group__bar"></i>
                        </div>
                    </div>
                </div>

                <div class="visible-xs-block" style="height: 5px"></div>
                <div class="col-sm-12 col-md-2 col-lg-2">
                    <div class="form-group">
                        <button class="btn btn-info">
                            <i class="zmdi zmdi-search"></i>
                            <?= $this->translate('Search') ?>
                        </button>
                    </div>
                </div>
            </div>
        </form>
        <div class="bootgrid-footer container-fluid">
            <div class="actionBar">
                <div class="search">
                    <?php
                    echo str_replace(
                        ['{current}', '{total}'],
                        [$currentItem ?? 0, $totalItem ?? 0],
                        $this->translate('Display {current} of {total} items')
                    );
                    ?>
                </div>
            </div>
        </div>
        <form method="post" id="adminForm" enctype="application/x-www-form-urlencoded">
            <div class="table-responsive">
                <table class="table table-hover table-bordered cst-badge">
                    <thead>
                        <tr>
                            <th width="100" class="text-center">
                                <?= $this->translate('No.') ?>
                            </th>
                            <th class="text-center">
                                <?= $this->translate('Region title') ?>
                            </th>
                            <th class="text-center">
                                <?= $this->translate('Tab name') ?>
                            </th>
                            <th width="120" class="text-center">
                                <?= $this->translate('Usable') ?>
                            </th>
                            <th width="100" class="text-center">
                                <?= $this->translate('Management') ?>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if ($totalItem):
                            $no = 1;
                            $confirmChangeStatus = $this->translate('You want to change state of this row?');
                            $confirmArr = htmlspecialchars(json_encode([
                                $this->translate('Show this category to the user. Are you really sure?'),
                                $this->translate('Hide this category. Are you really sure?'),
                            ]));
                            $delMsg = $this->translate('Delete this category. This operation cannot be undone. Do you really want to delete this?');
                            $no = 1;

                            foreach ($paginator as $item):
                                $id = $item->ga_id ?? '';
                                ?>
                                <tr>
                                    <td class="text-center">
                                        <input type="text" class="numeric integer fc-alt form-control input-md order-input"
                                            maxlength="3" name="order[<?= $id ?>]" value="<?= $item->ga_order ?? ''; ?>">
                                    </td>

                                    <td><?= $item->ga_title ?? '' ?> </td>

                                    <td><?= $item->ga_name ?? ''?></td>

                                    <td align="center" style="vertical-align: middle;">
                                        <a class="status-btn btn <?php
                                        if (1 == ($item->ga_status ?? 0)) {
                                            echo ' btn-success ';
                                            $icon = ' zmdi-check';
                                        } else {
                                            echo ' btn-danger ';
                                            $icon = ' zmdi-close';
                                        } ?> btn--icon" href="javascript:void(0);" data-url="<?=
                                             $this->zfUrl($routeName, [
                                                 'action' => 'change-status',
                                                 'pid' => $item->ga_parent_id ?? '',
                                                 'id' => $id,
                                             ])
                                             ?>" data-title="注意" data-confirm-arr="<?= $confirmArr ?>"
                                            data-btn-status="<?= 1 - ($item->ga_status ?? 0) ?>">
                                            <i class="zmdi <?= $icon ?>"></i>
                                        </a>
                                    </td>

                                    <td align="center" style="vertical-align: middle; white-space:nowrap;">
                                        <?php
                                        echo $this->manageIcon(
                                            'glyphicon glyphicon-list',
                                            [
                                                'href' => $this->zfUrl($routeName, ['action' => 'small', 'pid' => $id]),
                                                'aclass' => 'btn-info cate-child'
                                            ]
                                        ) . '&nbsp;';

                                        echo $this->manageUpdate(
                                            $this->zfUrl($routeName, [
                                                'action' => 'edit',
                                                'id' => $id,
                                                'pid' => $item->ga_parent_id ?? '',
                                            ])
                                        );
                                        ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                    </tbody>
                    <?php else: ?>
                        <tbody>
                            <tr>
                                <td colspan="100">
                                    <?= $this->translate('Data not found.'); ?>
                                </td>
                            </tr>
                        </tbody>
                    <?php endif; ?>
                </table>
            </div>
            <div class="pagination-outside">
                <div class="bootgrid-footer container-fluid">
                    <?= $totalItem > 0 ? $this->paginationControl(
                        $paginator,
                        'Sliding',
                        'application/partial/paginator',
                        ['route' => $routeName]
                    ) : ''?>
                </div>
            </div>
        </form>
    </div>
</div>