<?php
$this->headerSession()->setActiveItemId($activeItemId);
$this->headScriptAction(null, [], [
    'action' => 'index',
    'controller' => 'index',
    'module' => 'portfolio'
]);
$data = [
    [
        'size' => [630,1002],
        'name' => 'Port 1',
        'src'  => '/assets/customer/images/source/port-1.jpg',
    ],
    [
        'size' => [1260,501],
        'name' => 'Port 2',
        'src'  => '/assets/customer/images/source/gdtography-310706-unsplash.jpg',
    ],
    [
        'size' => [630,501],
        'name' => 'Port 3',
        'src'  => '/assets/customer/images/source/shutterstock_627788162.jpg',
    ],
    [
        'size' => [630,1002],
        'name' => 'Port 4',
        'src'  => '/assets/customer/images/source/hutomo-abrianto-576207-unsplash.jpg',
    ],
    [
        'size' => [1260,501],
        'name' => 'Port 5',
        'src'  => '/assets/customer/images/source/shutterstock_578977615.jpg',
    ],
    [
        'size' => [630,501],
        'name' => 'Port 6',
        'src'  => '/assets/customer/images/source/shutterstock_631879034.jpg',
    ],
    [
        'size' => [630,501],
        'name' => 'Port 7',
        'src'  => '/assets/customer/images/source/tobias-van-schneider-230813-unsplash.jpg',
    ],
    [
        'size' => [630,501],
        'name' => 'Port 8',
        'src'  => '/assets/customer/images/source/davide-cantelli-240809-unsplash.jpg',
    ],
];
?>
<div class="inteco-page-title-wrap inteco-style-medium inteco-center-align">
    <div class="inteco-header-transparent-substitute"></div>
    <div class="inteco-page-title-overlay"></div>
    <div class="inteco-page-title-container inteco-container">
        <div class="inteco-page-title-content inteco-item-pdlr">
            <h1 class="inteco-page-title"><?= $this->translate('Portfolio')?></h1>
        </div>
    </div>
</div>
<div class="inteco-page-wrapper" id="inteco-page-wrapper">
    <div class="gdlr-core-page-builder-body">
        <div class="gdlr-core-pbf-wrapper">
            <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
                <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
                    <div class="gdlr-core-pbf-column gdlr-core-column-30 gdlr-core-column-first"
                        id="gdlr-core-column-1">
                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js"
                            data-sync-height="height-1">
                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js  gdlr-core-sync-height-content">
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-4">
                                        <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-about">
                                            <?= $this->translate('Chúng tôi là ai')?>    
                                        </span>
                                        <div class="gdlr-core-title-item-title-wrap ">
                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-about">
                                                <?= $this->translate('Tiểu sử')?>
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align">
                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider" style="border-color: #d6c5c2 ;">
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div
                                        class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align">
                                        <div class="gdlr-core-text-box-item-content gdlr-core-text-box-item-content-service ">
                                            <?php echo $this->partial('partial/item-our-story.phtml')?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="gdlr-core-pbf-column gdlr-core-column-30" id="gdlr-core-column-2">
                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js"
                            data-sync-height="height-1">
                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js  gdlr-core-sync-height-content">
                                <?php if (DEVICE_ENV != 1): ?>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-4">
                                        <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-about">
                                            &nbsp;  
                                        </span>
                                        <div class="gdlr-core-title-item-title-wrap ">
                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-about">
                                            &nbsp;
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                                <?php endif; ?>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align">
                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider" style="border-color: #d6c5c2 ;">
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-pbf-column gdlr-core-column-20">
                                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js py-0">
                                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js">
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-1">
                                                        <div class="gdlr-core-title-item-title-wrap ">
                                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-portfolio-detail">
                                                                <?= $this->translate('Loại dịch vụ')?>
                                                            </h3>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-2">
                                                        <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption-portfolio-detail">
                                                            <?= $this->translate('Công trình cải tạo')?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="gdlr-core-pbf-column gdlr-core-column-20">
                                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js py-0">
                                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js">
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-1">
                                                        <div class="gdlr-core-title-item-title-wrap ">
                                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-portfolio-detail">
                                                                <?= $this->translate('Loại dự án')?>
                                                            </h3>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-2">
                                                        <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption-portfolio-detail">
                                                            <?= $this->translate('Nhà phố')?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="gdlr-core-pbf-column gdlr-core-column-20">
                                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js py-0">
                                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js">
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-1">
                                                        <div class="gdlr-core-title-item-title-wrap ">
                                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-portfolio-detail">
                                                                <?= $this->translate('Ví trí')?>
                                                            </h3>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-2">
                                                        <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption-portfolio-detail">
                                                            <?= $this->translate('Dương Cát Lợi, thi trấn Nhà Bè, TPHCM')?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="gdlr-core-pbf-column gdlr-core-column-20">
                                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js py-0">
                                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js">
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-1">
                                                        <div class="gdlr-core-title-item-title-wrap ">
                                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-portfolio-detail">
                                                                <?= $this->translate('Người phụ trách')?>
                                                            </h3>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="gdlr-core-pbf-element">
                                                    <div class="gdlr-core-title-item clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-2">
                                                        <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption-portfolio-detail">
                                                            <?= $this->translate('Nguyễn Văn Vân')?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align">
                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider" style="border-color: #d6c5c2 ;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                    </div>
                </div>
            </div>
         </div>
        <?php echo $this->partial('partial/block-portfolio.phtml', ['data' => $data ?? [], 'isShow' => false]);?>
    </div>
</div>