<?php 
$this->layout('layout/login');
$this->headTitle('Quyền truy cập bị từ chối! Vui lòng đăng nhập vào giờ làm việc hợp lệ hoặc địa chỉ IP hợp lệ.');
?>
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg mt-0">
    <div class="page-header align-items-start min-vh-100"
    style="background-image: url('/assets/manager/images/bg-500-error.jpg');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-12 m-auto text-center">
                    <h1 class="display-1 text-bolder text-white"><?= $this->translate('Error 404')?></h1>
                    <h2 class="text-white"><?=$this->translate('Quyền truy cập bị từ chối! Vui lòng đăng nhập vào giờ làm việc hợp lệ hoặc địa chỉ IP hợp lệ.');?></h2>
                    <button type="button" class="btn btn-outline-white mt-4"
                        onClick="document.location.href = '<?= $this->zfUrl('login') ?>';"
                    >
                        <?=$this->translate('Về trang chủ');?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</main>