<?php
$this->headerSession()->setActiveItemId($activeItemId);
$this->headScriptAction(null, [], [
    'action' => 'index',
    'controller' => 'index',
    'module' => 'blog'
]);
?>
<div class="inteco-page-title-wrap  inteco-style-custom inteco-center-align">
    <div class="inteco-header-transparent-substitute"></div>
    <div class="inteco-page-title-overlay"></div>
    <div class="inteco-page-title-container inteco-container">
        <div class="inteco-page-title-content inteco-item-pdlr">
            <h1 class="inteco-page-title">Blog</h1>
        </div>
    </div>
</div>
<div class="inteco-page-wrapper" id="inteco-page-wrapper">
    <div class="gdlr-core-page-builder-body">
        <div class="gdlr-core-pbf-wrapper ">
            <div class="gdlr-core-pbf-background-wrap gdlr-core-pbf-background-wrap-blog" ></div>
            <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
                <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
                    <div class="gdlr-core-pbf-element">
                        <div class="gdlr-core-blog-item gdlr-core-item-pdb clearfix gdlr-core-style-blog-column-with-frame py-4">
                            <div class="gdlr-core-blog-item-holder gdlr-core-js-2 clearfix" data-layout="fitrows">
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['action' => 'detail', 'param' => 'detail', 'id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-item-list gdlr-core-item-pdlr gdlr-core-column-<?= DEVICE_ENV == 2 ? 30 : 20?>">
                                    <div class="gdlr-core-blog-grid gdlr-core-blog-grid-with-frame gdlr-core-item-mgb gdlr-core-skin-e-background gdlr-core-js" data-sync-height="blog-item-1">
                                        <div class="gdlr-core-blog-thumbnail gdlr-core-media-image gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>">
                                                <img src="/assets/customer/images/source/etienne-beauregard-riverin-48305-unsplash-700x430.jpg" 
                                                    alt="" width="700" height="430" title="Image Title" />
                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-grid-frame p-3">
                                            <div class="gdlr-core-blog-grid-title-wrap">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title">
                                                    <a href="<?= $this->zfUrl('blog', ['param' => 'detail', 'id' => 1])?>"><?= $this->translate('Cách tìm sàn cho ngôi nhà của bạn')?></a>
                                                </h3>
                                                <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider">
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date">
                                                        <a href="#">June 6, 2016</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author">
                                                        <span class="gdlr-core-head" >By</span>
                                                        <a href="#" title="Posts by John Smith" rel="author">John Smith</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-category">
                                                        <span class="gdlr-core-head" >In</span>
                                                        <a href="#" rel="tag">Blog</a>
                                                    </span>
                                                    <span class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-comment-number">
                                                        <span class="gdlr-core-head" ><i class="fa fa-comments-o" ></i></span>
                                                        <a href="##respond">2 </a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="gdlr-core-blog-content">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring 
                                                which I enjoy with my whole heart. I am alone in...
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="gdlr-core-pagination gdlr-core-style-circle gdlr-core-left-align gdlr-core-item-pdlr">
                                <span aria-current='page' class='page-numbers current'>1</span>
                                <a class='page-numbers' href='#'>2</a>
                                <a class="next page-numbers" href="#"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>