<footer>
    <div class="inteco-footer-wrapper">
        <div class="inteco-footer-container inteco-container clearfix">
            <div class="inteco-footer-column inteco-item-pdlr inteco-column-15">
                <div id="text-1" class="widget widget_text inteco-widget">
                    <div class="textwidget">
                        <p>
                            <img class="alignnone size-full wp-image-5803" src="/assets/customer/images/source/footer-logo.png"
                                alt="Logo" width="120" height="24"/><br/>
                            <span class="gdlr-core-space-shortcode" style="margin-top: -27px ;"></span><br /> 
                            A wonderful serenity has taken possession of my entire soul, like these sweet morn
                            ings of spring which I enjoy with my whole heart of me.
                        </p>
                    </div>
                </div>
            </div>
            <div class="inteco-footer-column inteco-item-pdlr inteco-column-15">
                <div id="nav_menu-2" class="widget widget_nav_menu inteco-widget">
                    <h3 class="inteco-widget-title">Services</h3><span class="clear"></span>
                    <div class="menu-services-container">
                        <ul id="menu-services" class="menu">
                            <li class="menu-item"><a href="#">Architectural Design</a></li>
                            <li class="menu-item"><a href="#">Interior Design</a></li>
                            <li class="menu-item"><a href="#">Lighting Design</a></li>
                            <li class="menu-item"><a href="#">AutoCAD Service</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="inteco-footer-column inteco-item-pdlr inteco-column-15">
                <div id="nav_menu-1" class="widget widget_nav_menu inteco-widget">
                    <h3 class="inteco-widget-title">Quick Links</h3><span class="clear"></span>
                    <div class="menu-quick-links-container">
                        <ul id="menu-quick-links" class="menu">
                            <li class="menu-item"><a href="about-us.html">About Us</a></li>
                            <li class="menu-item"><a href="#">Service</a></li>
                            <li class="menu-item"><a href="price-table.html">Price Table</a></li>
                            <li class="menu-item"><a href="get-a-quote.html">Get A Quote</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="inteco-footer-column inteco-item-pdlr inteco-column-15">
                <div id="gdlr-core-recent-portfolio-widget-2"
                    class="widget widget_gdlr-core-recent-portfolio-widget inteco-widget">
                    <h3 class="inteco-widget-title">Recent Works</h3><span class="clear"></span>
                    <div class="gdlr-core-recent-portfolio-widget-wrap clearfix">
                        <div class="gdlr-core-recent-portfolio-widget gdlr-core-media-image">
                            <a href="#">
                                <img src="/assets/customer/images/source/port-1-150x150.jpg" alt="" width="150"
                                    height="150" title="port-1" />
                                <span class="gdlr-core-image-overlay ">
                                    <i class="gdlr-core-image-overlay-icon gdlr-core-size-15 icon_link_alt"></i>
                                </span>
                            </a>
                        </div>
                        <div class="gdlr-core-recent-portfolio-widget gdlr-core-media-image">
                            <a href="#">
                                <img src="/assets/customer/images/source/gdtography-310706-unsplash-150x150.jpg" alt=""
                                    width="150" height="150" title="gdtography-310706-unsplash" />
                                <span class="gdlr-core-image-overlay ">
                                    <i class="gdlr-core-image-overlay-icon gdlr-core-size-15 icon_link_alt"></i>
                                </span>
                            </a>
                        </div>
                        <div class="gdlr-core-recent-portfolio-widget gdlr-core-media-image">
                            <a href="#">
                                <img src="/assets/customer/images/source/shutterstock_627788162-150x150.jpg" alt=""
                                    width="150" height="150" title="shutterstock_627788162" />
                                <span class="gdlr-core-image-overlay ">
                                    <i class="gdlr-core-image-overlay-icon gdlr-core-size-15 icon_link_alt"></i>
                                </span>
                            </a>
                        </div>
                        <div class="gdlr-core-recent-portfolio-widget gdlr-core-media-image">
                            <a href="#">
                                <img src="/assets/customer/images/source/hutomo-abrianto-576207-unsplash-150x150.jpg"
                                    alt="" width="150" height="150" title="hutomo-abrianto-576207-unsplash" />
                                <span class="gdlr-core-image-overlay ">
                                    <i class="gdlr-core-image-overlay-icon gdlr-core-size-15 icon_link_alt"></i>
                                </span>
                            </a>
                        </div>
                        <div class="gdlr-core-recent-portfolio-widget gdlr-core-media-image">
                            <a href="#">
                                <img src="/assets/customer/images/source/shutterstock_578977615-150x150.jpg" alt=""
                                    width="150" height="150" title="shutterstock_578977615" />
                                <span class="gdlr-core-image-overlay ">
                                    <i class="gdlr-core-image-overlay-icon gdlr-core-size-15 icon_link_alt"></i>
                                </span>
                            </a>
                        </div>
                        <div class="gdlr-core-recent-portfolio-widget gdlr-core-media-image">
                            <a href="#">
                                <img src="/assets/customer/images/source/shutterstock_631879034-150x150.jpg" alt=""
                                    width="150" height="150" title="shutterstock_631879034" />
                                <span class="gdlr-core-image-overlay ">
                                    <i class="gdlr-core-image-overlay-icon gdlr-core-size-15 icon_link_alt"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="inteco-copyright-wrapper">
        <div class="inteco-copyright-container inteco-container clearfix">

            <div class="inteco-copyright-left inteco-item-pdlr">
                <a href="#" target="_blank">
                    <i class="fa fa-facebook gdlr-core-social-network-footer"></i>
                </a>
                <a href="#" target="_blank">
                    <i class="fa fa-twitter gdlr-core-social-network-footer"></i>
                </a>
                <a href="#" target="_blank">
                    <i class="fa fa-linkedin gdlr-core-social-network-footer"></i>
                </a>
                <a href="#" target="_blank">
                    <i class="fa fa-instagram gdlr-core-social-network-footer"></i>
                </a>
            </div>
            <div class="inteco-copyright-right inteco-item-pdlr">Copyright 2023, max-themes. All right reserved</div>
        </div>
    </div>
</footer>