<div class="inteco-mobile-header-wrap">
	<div class="inteco-mobile-header inteco-header-background inteco-style-slide inteco-sticky-mobile-navigation"
		id="inteco-mobile-header">
		<div class="inteco-mobile-header-container inteco-container clearfix">
			<div class="inteco-logo  inteco-item-pdlr">
				<div class="inteco-logo-inner">
					<a href="<?= $this->zfUrl('home') ?>">
						<img src="/assets/customer/images/source/logo.png" alt="Logo" width="200" height="39" title="logo" />
					</a>
				</div>
			</div>
			<div class="inteco-mobile-menu-right">
				<div class="inteco-overlay-menu inteco-mobile-menu" id="inteco-mobile-menu">
					<a class="inteco-overlay-menu-icon inteco-mobile-menu-button inteco-mobile-button-hamburger"
						href="#"><span></span></a>
					<div class="inteco-overlay-menu-content inteco-navigation-font">
						<div class="inteco-overlay-menu-close"></div>
						<div class="inteco-overlay-menu-row">
							<div class="inteco-overlay-menu-cell inteco-navigation">
								<ul id="menu-main-navigation" class="menu">
									<?= $menuItems ?>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="inteco-header-background-transparent">
	<header
		class="inteco-header-wrap inteco-header-style-plain  inteco-style-float-left inteco-sticky-navigation inteco-style-slide"
		data-navigation-offset="75px">
		<div class="inteco-header-background"></div>
		<div class="inteco-header-container  inteco-header-full">

			<div class="inteco-header-container-inner clearfix">
				<div class="inteco-logo  inteco-item-pdlr">
					<div class="inteco-logo-inner">
						<a class="" href="index.html"><img src="/assets/customer/images/source/logo.png" alt="" width="200"
								height="39" title="logo" /></a>
					</div>
					<div class="inteco-logo-bottom-divider" id="inteco-logo-bottom-divider"></div>
				</div>
				<div class="inteco-navigation inteco-item-pdlr clearfix ">
					<div class="inteco-main-menu" id="inteco-main-menu">
						<ul id="menu-main-navigation-1" class="sf-menu">
							<?= $menuItemsDeskTop ?>
						</ul>
					</div>
				</div>
				<!-- inteco-navigation -->

				<div class="inteco-header-right-social gdlr-core-item-pdlr">
					<a href="#" target="_blank" class="inteco-top-bar-social-icon" title="facebook">
						<i class="fa fa-facebook"></i>
					</a>
					<a href="#" target="_blank" class="inteco-top-bar-social-icon" title="twitter">
						<i class="fa fa-twitter"></i>
					</a>
					<a href="#" target="_blank" class="inteco-top-bar-social-icon" title="linkedin">
						<i class="fa fa-linkedin"></i>
					</a>
					<a href="#" target="_blank" class="inteco-top-bar-social-icon" title="instagram">
						<i class="fa fa-instagram"></i>
					</a>
				</div>
			</div>
			<!-- inteco-header-inner -->
		</div>
		<!-- inteco-header-container -->
	</header>
	<!-- header -->
</div>