<?php 
$pubRes = $this->zfResource();
echo $this->doctype('HTML5');
?>
<html lang="<?= APPLICATION_LANGUAGE?>">
    <head>
       <meta charset="utf-8">
        <?= $this->headTitle(WEB_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->setHttpEquiv('Content-Type', 'text/html; charset=utf-8')
            ->appendName('viewport', 'height=device-height,width=device-width,initial-scale=1.0,maximum-scale=1.0, user-scalable=no, shrink-to-fit=no')
            ->setHttpEquiv('X-UA-Compatible', 'IE=EDGE')
            ->appendName('copyright', WEB_NAME.', Inc')
            ->appendName('author', WEB_NAME.', Inc')
            ->appendName('keywords', WEB_NAME.', Inc')
            ->appendName('description', 'Sỹ Tùng đẹp trai vãi nồi')

            ->appendName('twitter:card', WEB_NAME.', Inc')
            ->appendName('twitter:site', WEB_NAME.', Inc')
            ->appendName('twitter:title', WEB_NAME.', Inc')
            ->appendName('twitter:description', 'Sỹ Tùng đẹp trai vãi nồi')
            ->appendName('twitter:creator', WEB_NAME.', Inc')
            ->appendName('twitter:image', WEB_NAME.', Inc')

            ->appendProperty('fb:app_id', '655968634437471')
            ->appendProperty('og:title', WEB_NAME.', Inc')
            ->appendProperty('og:type', WEB_NAME.', Inc')
            ->appendProperty('og:url', WEB_NAME.', Inc')
            ->appendProperty('og:image', WEB_NAME.', Inc')
            ->appendProperty('og:description', 'Sỹ Tùng đẹp trai vãi nồi')
            ->appendProperty('og:site_name', WEB_NAME.', Inc')
            ->setAutoEscape(false)
        ?>
        <link rel="shortcut icon" type="image/png" href="<?=
            $pubRes->files('favicon.png', 'images', false)?>"/>
        <link rel='stylesheet' id='gdlr-core-google-font-css' 
            href='https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A200%2C200italic%2C300%2C300italic%2Cregular%2Citalic%2C600%2C600italic%2C700%2C700italic%2C900%2C900italic&amp;subset=cyrillic-ext%2Cvietnamese%2Clatin%2Ccyrillic%2Cgreek-ext%2Clatin-ext%2Cgreek&amp;ver=5.0.2' 
            type='text/css' media='all' />
        <?php 

        $isDebug = $_GET['not-minify'] ?? 0;
        $cssMinifyMethod = 'minifyHeadLink';
        if ( $isDebug ) $cssMinifyMethod = 'headLink';

        // -- custom css and jquery
        $cssNo = 0; $jsNo = 0;

        $assetsItems = [
            'css' => array_replace([
                ($cssNo+=10) => $pubRes->files( 'block.min.css', 'css', false),
                ($cssNo+=10) => $pubRes->files( 'goodlayers-core/plugins/combine/style.css', 'js', false),
                ($cssNo+=10) => $pubRes->files( 'revslider/public/assets/css/settings.css', 'js', false),
                ($cssNo+=10) => $pubRes->files( 'style-core.css', 'css', false),
                ($cssNo+=10) => $pubRes->files( 'style-custom.css', 'css', false),
                ($cssNo+=10) => $pubRes->files( 'page-builder.css', 'css', false),
            ], $cstAsset['css']),
           'js' => array_replace([
                ($jsNo+=10) => $pubRes->files( 'jquery/jquery.js', 'js', false),
                ($jsNo+=10) => $pubRes->files( 'jquery/jquery-migrate.min.js', 'js', false),
                ($jsNo+=10) => $pubRes->files( 'goodlayers-core/plugins/combine/script.js', 'js', false),
                ($jsNo+=10) => $pubRes->files( 'goodlayers-core/include/js/page-builder.js', 'js', false),
                ($jsNo+=10) => $pubRes->files( 'jquery/ui/effect.min.js', 'js', false),
                ($jsNo+=10) => $pubRes->files( 'plugins.js', 'js', false),
            ], $cstAsset['js'])
        ];
        ksort($assetsItems['css']);
        foreach ($assetsItems['css'] as $css)
            $this->{$cssMinifyMethod}() ->appendStylesheet($css, 'all');
        echo $this->{$cssMinifyMethod}()->setAutoEscape(false) . "\n";

        // -- Render custom css
        echo $this->headStyle();
        ?>
    </head>
    <body class="home page-template-default page page-id-2039 gdlr-core-body woocommerce-no-js inteco-body inteco-body-front inteco-full  inteco-with-sticky-navigation  inteco-blockquote-style-1 gdlr-core-link-to-lightbox">
        <?= $this->content; ?>
        <?php
    	// Add files JS.
	    $jsMinifyMethod = 'minifyHeadScript';
	    if ( $isDebug ) $jsMinifyMethod = 'headScript';
	    ksort($assetsItems['js']);
	    $assetsItems['js'] = array_reverse($assetsItems['js']);
    	foreach ($assetsItems['js'] as $js)
    	   $this ->{$jsMinifyMethod}()->prependFile($js);
	    echo $this ->{$jsMinifyMethod}()->setAutoEscape(false) . "\n";

        if ($isDebug) echo $this->inlinescript();

        $flashMessenger = $this->flashMessenger();
        // Get messages from Zend_Action_Helper_FlashMessenger.
		$flashMessengers = array_filter([
		    'info' => array_merge(
		        $flashMessenger->getCurrentInfoMessages(),
		        $flashMessenger->getInfoMessages()
	        ),
		    'success' => array_merge(
		        $flashMessenger->getCurrentSuccessMessages(),
		        $flashMessenger->getSuccessMessages()
	        ),
		    'warning' => array_merge(
		        $flashMessenger->getCurrentWarningMessages(),
		        $flashMessenger->getWarningMessages()
	        ),
		    'danger' => array_merge(
		        $flashMessenger->getCurrentErrorMessages(),
		        $flashMessenger->getErrorMessages()
	        )
		]);

		// Clear message
		$flashMessenger->clearCurrentMessagesFromContainer();
        ?>
        <?php unset($pubRes, $menuHeader); ?>
    </body>
</html>