<?php 
$this->headerSession()->setActiveItemId($activeItemId);
?>
<div class="inteco-page-wrapper" id="inteco-page-wrapper">
    <div class="gdlr-core-page-builder-body">
        <div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-contact"
            id="gdlr-core-wrapper-1">
            <div class="gdlr-core-pbf-background-wrap">
                <div class="gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js gdlr-core-img-background "
                    style="background-image: url(/assets/customer/images/source/getquote-bg.jpg);"
                    data-parallax-speed="0.3"></div>
            </div>
            <div class="gdlr-core-pbf-wrapper-content gdlr-core-js " data-gdlr-animation="fadeIn"
                data-gdlr-animation-duration="600ms" data-gdlr-animation-offset="0.8">
                <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container-custom max-width-730">
                    <div class="gdlr-core-pbf-element">
                        <div
                            class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr">
                            <div class="gdlr-core-title-item-title-wrap ">
                                <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-contact">
                                    <?= $this->translate('Liên hệ')?>
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-contact">
            <div class="gdlr-core-pbf-background-wrap gdlr-core-pbf-background-wrap-project"></div>
            <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
                <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
                    <div class="gdlr-core-pbf-column gdlr-core-column-40 gdlr-core-column-first">
                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-margin-contact">
                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr py-3">
                                        <div class="gdlr-core-title-item-title-wrap ">
                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-accordion-item-title-custom">
                                                <?= $this->translate('Gửi yêu cầu báo giá vào biểu mẫu này')?>
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align py-4">
                                        <div class="gdlr-core-text-box-item-content gdlr-core-text-box-item-content-contact">
                                            <p>A wonderful serenity has taken possession of my entire soul, like these
                                                sweet mornings of spring which I enjoy with my whole heart. I am alone,
                                                and feel the charm of existence in this spot, which was created for the
                                                bliss of souls like mine.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-contact-form-7-item gdlr-core-item-pdlr gdlr-core-item-pdb ">
                                        <div role="form" class="wpcf7" id="wpcf7-f5826-p5822-o1" lang="en-US" dir="ltr">
                                            <div class="screen-reader-response"></div>
                                            <form action="" method="post">
                                                <div class="gdlr-core-input-wrap gdlr-core-large gdlr-core-full-width gdlr-core-with-column gdlr-core-no-border">
                                                    <div class="gdlr-core-column-60">
                                                        <span class="name">
                                                            <input type="text"
                                                                name="your-name" value="" size="40"
                                                                placeholder="Full Name*" />
                                                        </span>
                                                    </div>
                                                    <div class="clear"></div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="email">
                                                            <input type="email" name="your-email" value="" size="40"
                                                                placeholder="Email*" />
                                                        </span>
                                                    </div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="address">
                                                            <input type="text" name="your-address" value="" size="40"
                                                                placeholder="Address*" />
                                                        </span>
                                                    </div>
                                                    <div class="clear"></div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="company">
                                                            <input type="text" name="your-company" value="" size="40"
                                                                placeholder="Company*" />
                                                        </span>
                                                    </div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="phone">
                                                            <input type="tel" name="your-phone" value="" size="40"
                                                                placeholder="Phone*" />
                                                        </span>
                                                    </div>
                                                    <div class="clear"></div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="area">
                                                            <input type="text" name="your-area" value="" size="40"
                                                                placeholder="Areas Of Interest*" />
                                                        </span>
                                                    </div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="budget">
                                                            <input type="text" name="your-budget" value="" size="40"
                                                                placeholder="Project Budget*" />
                                                        </span>
                                                    </div>
                                                    <div class="clear"></div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="date">
                                                            <input type="date"
                                                                name="your-date" value=""
                                                                placeholder="Requested Completion Date*" />
                                                        </span>
                                                    </div>
                                                    <div class="gdlr-core-column-30">
                                                        <span class="refer">
                                                            <input type="text" name="your-refer" value="" size="40"
                                                                placeholder="Referred By" />
                                                        </span>
                                                    </div>
                                                    <div class="clear"></div>
                                                    <div class="gdlr-core-column-60">
                                                        <span class="message">
                                                            <textarea  name="your-message" cols="40" rows="10"
                                                                placeholder="Tell us about your project*">
                                                            </textarea>
                                                        </span>
                                                    </div>
                                                    <div class="clear"></div>
                                                    <div class="gdlr-core-column-60 gdlr-core-left-align">
                                                        <input type="submit" value="Submit Now" class="gdlr-core-full" />
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="gdlr-core-pbf-column gdlr-core-column-20">
                        <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-margin-contact">
                            <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr py-4">
                                        <div class="gdlr-core-title-item-title-wrap ">
                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-contact-detail">
                                                <?= $this->translate('Địa chỉ')?>
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align py-0">
                                        <div class="gdlr-core-text-box-item-content" style="font-size: 16px ;">
                                            <p>230, Phạm Hữu Lầu, Q7, TPHCM</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div
                                        class="gdlr-core-icon-list-item gdlr-core-item-pdlr gdlr-core-item-pdb clearfix ">
                                        <ul>
                                            <li class=" gdlr-core-skin-divider">
                                                <span class="gdlr-core-icon-list-icon-wrap mx-2">
                                                    <i class="gdlr-core-icon-list-icon gdlr-core-icon-list-icon-contact fa fa-envelope-o"></i>
                                                </span>
                                                <div class="gdlr-core-icon-list-content-wrap">
                                                    <span class="gdlr-core-icon-list-content fs-6">contact@kietdecor@gmail.com</span>
                                                </div>
                                            </li>
                                            <li class=" gdlr-core-skin-divider">
                                                <span class="gdlr-core-icon-list-icon-wrap mx-2">
                                                    <i class="gdlr-core-icon-list-icon gdlr-core-icon-list-icon-contact fa fa-phone"></i>
                                                </span>
                                                <div class="gdlr-core-icon-list-content-wrap">
                                                    <span class="gdlr-core-icon-list-content fs-6">+0964-938-735</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr py-4">
                                        <div class="gdlr-core-title-item-title-wrap ">
                                            <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-contact-detail">
                                               <?= $this->translate('Giờ hoạt động')?>
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-element">
                                    <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align py-0"
                                        style="padding-bottom: 0px ;">
                                        <div class="gdlr-core-text-box-item-content gdlr-core-text-box-item-content-contact">
                                            <p>We are open on <strong>Monday – Friday at 11am and 3pm</strong>, except
                                                on holidays.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="gdlr-core-pbf-wrapper p-0">
            <div class="gdlr-core-pbf-background-wrap"></div>
            <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
                <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-pbf-wrapper-full-no-space">
                    <div class="gdlr-core-pbf-element">
                        <div class="gdlr-core-wp-google-map-plugin-item gdlr-core-item-pdlr gdlr-core-item-pdb py-0">
                            <div style="overflow:hidden;width: 100%;position: relative;">
                                <iframe style="width:100%; height:480px; "
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d980.0088925155576!2d106.73668776961982!3d10.731739999338412!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175256fd07a94af%3A0x365a1f78bc90e87a!2zQ2h1bmcgQ8awIE5n4buNYyBMYW4!5e0!3m2!1svi!2s!4v1688275758085!5m2!1svi!2s"
                                    width="600" height="450" style="border:0;" allowfullscreen loading="lazy"></iframe>
                                <div style="position: absolute;width: 80%;bottom: 20px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;">

                                </div>
                                <style>
                                    #gmap_canvas img {
                                        max-width: none !important;
                                        background: none !important
                                    }
                                </style>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-social">
            <div class="gdlr-core-pbf-background-wrap back-ground-white"></div>
            <div class="gdlr-core-pbf-wrapper-content gdlr-core-js " data-gdlr-animation="fadeInUp"
                data-gdlr-animation-duration="600ms" data-gdlr-animation-offset="0.8">
                <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-pbf-wrapper-full-no-space">
                    <div class="gdlr-core-pbf-element">
                        <div class="gdlr-core-social-network-item gdlr-core-item-pdb  gdlr-core-center-align gdlr-core-item-pdlr py-0">
                            <a href="mailto:#" target="_blank"
                                class="gdlr-core-social-network-icon gdlr-core-social-network-icon-contact" title="email">
                                <i class="fa fa-envelope"></i>
                            </a>
                            <a href="#" target="_blank" 
                                class="gdlr-core-social-network-icon gdlr-core-social-network-icon-contact" title="facebook">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a href="#" target="_blank"
                                class="gdlr-core-social-network-icon gdlr-core-social-network-icon-contact" title="google-plus">
                                <i class="fa fa-google-plus"></i>
                            </a>
                            <a href="#" target="_blank"
                                class="gdlr-core-social-network-icon gdlr-core-social-network-icon-contact" title="linkedin">
                                <i class="fa fa-linkedin"></i>
                            </a>
                            <a href="#" target="_blank"
                                class="gdlr-core-social-network-icon gdlr-core-social-network-icon-contact" title="skype">
                                <i class="fa fa-skype"></i>
                            </a>
                            <a href="#" target="_blank"
                                class="gdlr-core-social-network-icon gdlr-core-social-network-icon-contact" title="twitter">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>