<?php
$this->headerSession()->setActiveItemId($activeItemId);
?>
<div class="inteco-page-title-wrap  inteco-style-large inteco-center-align">
    <div class="inteco-header-transparent-substitute"></div>
    <div class="inteco-page-title-overlay"></div>
    <div class="inteco-page-title-container inteco-container">
        <div class="inteco-page-title-content inteco-item-pdlr">
            <h1 class="inteco-page-title"><?= $this->translate('Bảng giá')?></h1>
        </div>
    </div>
</div>
<div class="inteco-page-wrapper" id="inteco-page-wrapper">
    <div class="gdlr-core-page-builder-body">
        <div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-price">
            <div class="gdlr-core-pbf-background-wrap" style="background-color: #f1f1f1 ;"></div>
            <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
                <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
                    <div class="gdlr-core-pbf-element">
                        <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr">
                            <div class="gdlr-core-title-item-title-wrap ">
                                <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-price">
                                    <?= $this->translate('Bảng giá theo tính năng')?>
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="gdlr-core-pbf-element">
                        <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align py-5">
                            <div class="gdlr-core-text-box-item-content" style="font-size: 16px ;">
                                <p>Một sự thanh thản tuyệt vời đã chiếm hữu toàn bộ tâm hồn tôi, giống như những điều ngọt ngào này
                                    những buổi sáng mùa xuân mà tôi tận hưởng bằng cả trái tim mình. Tôi một mình, và cảm thấy sự quyến rũ
                                    về sự tồn tại ở vị trí này, nơi được tạo ra vì niềm hạnh phúc của những linh hồn như của tôi. Tôi là
                                    hạnh phúc quá, bạn thân mến, đắm chìm trong cảm giác tinh tế của sự yên tĩnh đơn thuần
                                    sự tồn tại, rằng tôi bỏ bê tài năng của mình. Tôi không có khả năng vẽ một
                                    đột quỵ ở thời điểm hiện tại</p>
                            </div>
                        </div>
                    </div>
                    <div class="gdlr-core-pbf-element">
                        <div class="gdlr-core-price-table-item gdlr-core-item-pdlr gdlr-core-item-pdb clearfix ">
                            <div class="gdlr-core-price-table-column gdlr-core-column-20">
                                <div class="gdlr-core-price-table">
                                    <div class="gdlr-core-price-table-head">
                                        <div class="gdlr-core-price-table-icon"><i class="fa fa-lightbulb-o"></i></div>
                                        <h3 class="gdlr-core-price-table-title">Starter Plan</h3>
                                        <div class="gdlr-core-price-table-caption">Suitable for starter</div>
                                    </div>
                                    <div class="gdlr-core-price-table-price gdlr-core-title-font">
                                        <span class="gdlr-core-price-prefix">$</span>
                                        <span class="gdlr-core-price-table-price-number">9.90</span>
                                        <span class="gdlr-core-price-suffix">/ MO</span>
                                    </div>
                                    <div class="gdlr-core-price-table-content-wrap">
                                        <div class="gdlr-core-price-table-content">
                                            <div class="gdlr-core-price-list-shortcode">
                                                <ul>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                </ul>
                                            </div>
                                        </div>
                                        <a class="gdlr-core-price-table-button gdlr-core-button" href="#"
                                            target="_self">Learn More</a>
                                    </div>
                                </div>
                            </div>
                            <div class="gdlr-core-price-table-column gdlr-core-column-20">
                                <div class="gdlr-core-price-table gdlr-core-active">
                                    <div class="gdlr-core-price-table-head">
                                        <div class="gdlr-core-price-table-icon"><i class="fa fa-codepen"></i></div>
                                        <h3 class="gdlr-core-price-table-title">Advanced Plan</h3>
                                        <div class="gdlr-core-price-table-caption">Suitable for profession</div>
                                    </div>
                                    <div class="gdlr-core-price-table-price gdlr-core-title-font">
                                        <span class="gdlr-core-price-prefix">$</span>
                                        <span class="gdlr-core-price-table-price-number">20</span>
                                        <span class="gdlr-core-price-suffix">/ MO</span>
                                    </div>
                                    <div class="gdlr-core-price-table-content-wrap">
                                        <div class="gdlr-core-price-table-content">
                                            <div class="gdlr-core-price-list-shortcode">
                                                <ul>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                </ul>
                                            </div>
                                        </div><a class="gdlr-core-price-table-button gdlr-core-button" href="#"
                                            target="_self">Learn More</a>
                                    </div>
                                </div>
                            </div>
                            <div class="gdlr-core-price-table-column gdlr-core-column-20">
                                <div class="gdlr-core-price-table ">
                                    <div class="gdlr-core-price-table-head">
                                        <div class="gdlr-core-price-table-icon"><i class="fa fa-connectdevelop"></i>
                                        </div>
                                        <h3 class="gdlr-core-price-table-title">Enterprise Plan</h3>
                                        <div class="gdlr-core-price-table-caption">Suitable for corporate</div>
                                    </div>
                                    <div class="gdlr-core-price-table-price gdlr-core-title-font">
                                        <span class="gdlr-core-price-prefix">$</span>
                                        <span class="gdlr-core-price-table-price-number">50</span>
                                        <span class="gdlr-core-price-suffix">/ MO</span>
                                    </div>
                                    <div class="gdlr-core-price-table-content-wrap">
                                        <div class="gdlr-core-price-table-content">
                                            <div class="gdlr-core-price-list-shortcode">
                                                <ul>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                    <li><i class="fa fa-check"></i>List item here</li>
                                                </ul>
                                            </div>
                                        </div><a class="gdlr-core-price-table-button gdlr-core-button" href="#"
                                            target="_self"><?= $this->translate('Xem thêm')?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>