<div class="gdlr-core-pbf-wrapper">
    <div class="gdlr-core-pbf-background-wrap">
        <div class="gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js"
            style="background-image: url(/assets/customer/images/source/hp1-about-bg-2-1.jpg) ;background-repeat: no-repeat ;background-position: center ;"
            data-parallax-speed="-0.2"></div>
    </div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-column gdlr-core-column-30 gdlr-core-column-first" id="gdlr-core-column-2">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-slogan-left">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "
                        data-gdlr-animation="fadeInLeft" data-gdlr-animation-duration="600ms"
                        data-gdlr-animation-offset="0.8">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr gdlr-core-title-item-caption-slogan">
                                <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-slogan">
                                    <?=$this->translate('Ý tưởng')?>
                                </span>
                                <div class="gdlr-core-title-item-title-wrap ">
                                    <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-story">
                                        <?=$this->translate('Sáng tạo')?>
                                    </h3>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align gdlr-core-item-pdlr-slogan">
                                <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                    style="border-color: #d6c5c2 ;">
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                style="padding-bottom: 0px ;">
                                <div class="gdlr-core-text-box-item-content text-transform-none" >
                                    <p>Một sự thanh thản tuyệt vời chiếm hữu toàn bộ tâm hồn tôi, giống như những buổi sáng 
                                        ngọt ngào của mùa xuân mà tôi tận hưởng bằng cả trái tim mình.</p>
                                    <p>
                                        <span style="color: #b6958e;">Tôi chỉ có một mình và cảm thấy sự quyến rũ của sự tồn tại ở nơi này
                                        </span>, nơi được tạo ra để mang lại niềm hạnh phúc cho những linh hồn như tôi. 
                                        Tôi rất hạnh phúc, bạn thân mến, quá đắm chìm trong cảm giác tinh tế của sự tồn tại đơn thuần yên tĩnh, 
                                        đến nỗi tôi bỏ bê tài năng của mình. Tôi không thể vẽ một nét nào vào thời điểm hiện tại; và tôi cảm thấy rằng tôi chưa bao giờ 
                                        là một nghệ sĩ vĩ đại hơn bây giờ. Khi, trong khi thung lũng đáng yêu.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-30">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-slogan-right">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "
                        data-gdlr-animation="fadeInRight" data-gdlr-animation-duration="600ms"
                        data-gdlr-animation-offset="0.8">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-image-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-right-align py-0">
                                <div class="gdlr-core-image-item-wrap gdlr-core-media-image gdlr-core-image-item-style-rectangle gdlr-core-image-item-slogan">
                                    <img src="/assets/customer/images/source/jean-philippe-delberghe-660138-unsplash-600x800.jpg" alt=""
                                        width="600" height="800" title="jean-philippe-delberghe-660138-unsplash" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-30 gdlr-core-column-first" id="gdlr-core-column-3">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-slogan-left-2">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "
                        data-gdlr-animation="fadeInLeft" data-gdlr-animation-duration="600ms"
                        data-gdlr-animation-offset="0.8">
                        <div class="gdlr-core-pbf-element">
                            <div
                                class="gdlr-core-image-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-right-align">
                                <div class="gdlr-core-image-item-wrap gdlr-core-media-image gdlr-core-image-item-style-rectangle gdlr-core-image-item-slogan">
                                    <img src="/assets/customer/images/source/armin-djuhic-609206-unsplash-600x800.jpg" alt="" width="600"
                                        height="800" title="armin-djuhic-609206-unsplash" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-30" id="gdlr-core-column-4">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-slogan-right-2">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "
                        data-gdlr-animation="fadeInRight" data-gdlr-animation-duration="600ms"
                        data-gdlr-animation-offset="0.8">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr gdlr-core-title-item-caption-slogan">
                                <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-slogan">
                                    <?=$this->translate('Chúng tôi tạo nên')?>
                                </span>
                                <div class="gdlr-core-title-item-title-wrap ">
                                    <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-story">
                                        <?=$this->translate('Sự khác biệt')?>
                                    </h3>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align gdlr-core-item-pdlr-slogan-2">
                                <div class="gdlr-core-divider-container" style="max-width: 355px ;">
                                    <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                        style="border-color: #d6c5c2 ;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                style="padding-bottom: 0px ;">
                                <div class="gdlr-core-text-box-item-content text-transform-none">
                                    <p>Một sự thanh thản tuyệt vời chiếm hữu toàn bộ tâm hồn tôi, giống như những buổi sáng ngọt ngào
                                         của mùa xuân mà tôi tận hưởng bằng cả trái tim mình.</p>
                                    <p><span style="color: #b6958e;">Tôi chỉ có một mình và cảm thấy sự quyến rũ của sự tồn tại ở nơi này</span>, 
                                    nơi được tạo ra để mang lại niềm hạnh phúc cho những linh hồn như tôi. Tôi rất hạnh phúc, bạn thân mến, 
                                    quá đắm chìm trong cảm giác tinh tế của sự tồn tại đơn thuần yên tĩnh, đến nỗi tôi bỏ bê tài năng của mình. 
                                    Tôi không thể vẽ một nét nào vào thời điểm hiện tại; và tôi cảm thấy rằng tôi chưa bao giờ là một nghệ sĩ 
                                    vĩ đại hơn bây giờ. Khi, trong khi thung lũng đáng yêu.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>