<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-project">
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js" data-gdlr-animation="fadeInDown"
        data-gdlr-animation-duration="600ms" data-gdlr-animation-offset="0.8">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-element">
                <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-5">
                    <div class="gdlr-core-title-item-title-wrap ">
                        <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-home">
                            <?=$this->translate('Portfolio')?>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-<?= DEVICE_ENV == 2 ? '30' : '20';?> gdlr-core-column-first">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-image-item gdlr-core-item-pdlr gdlr-core-item-pdb  gdlr-core-center-align">
                                <div class="gdlr-core-image-item-wrap gdlr-core-media-image gdlr-core-image-item-style-rectangle gdlr-core-image-item-home">
                                    <img src="/assets/customer/images/source/ruben-garcia-588365-unsplash-700x430.jpg" alt="" width="700"
                                        height="430" title="ruben-garcia-588365-unsplash" />
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr-home">
                                <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-home">
                                    <?=$this->translate('Thiết kế nột thất')?>
                                </span>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align py-0">
                                <div class="gdlr-core-text-box-item-content text-transform-none">
                                    <p>
                                        <?=$this->translate('Xin chào quý vị và các bạn, chúng tôi xin chân thành cảm ơn quý vị đã đến tham dự chương trình của chúng tôi.')?>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-button-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align">
                                <a class="gdlr-core-button gdlr-core-button-transparent gdlr-core-button-no-border gdlr-core-button-service"
                                    href="#">
                                    <span class="gdlr-core-content"><?=$this->translate('Xem thêm')?></span>
                                    <i class="gdlr-core-pos-right gdlr-core-pos-right-color-main fa fa-long-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-<?= DEVICE_ENV == 2 ? '30' : '20';?>">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-image-item gdlr-core-item-pdlr gdlr-core-item-pdb  gdlr-core-center-align">
                                <div class="gdlr-core-image-item-wrap gdlr-core-media-image gdlr-core-image-item-style-rectangle gdlr-core-image-item-home">
                                    <img src="/assets/customer/images/source/shutterstock_578977615-700x430.jpg" alt="" width="700"
                                        height="430" title="ruben-garcia-588365-unsplash" />
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr-home">
                                <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-home">
                                    <?=$this->translate('Thiết kế nột thất')?>
                                </span>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align py-0">
                                <div class="gdlr-core-text-box-item-content text-transform-none">
                                    <p>
                                        <?=$this->translate('Xin chào quý vị và các bạn, chúng tôi xin chân thành cảm ơn quý vị đã đến tham dự chương trình của chúng tôi.')?>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-button-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align">
                                <a class="gdlr-core-button gdlr-core-button-transparent gdlr-core-button-no-border gdlr-core-button-service"
                                    href="#">
                                    <span class="gdlr-core-content"><?=$this->translate('Xem thêm')?></span>
                                    <i class="gdlr-core-pos-right gdlr-core-pos-right-color-main fa fa-long-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>      
            <div class="gdlr-core-pbf-column gdlr-core-column-<?= DEVICE_ENV == 2 ? '30' : '20';?>">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-image-item gdlr-core-item-pdlr gdlr-core-item-pdb  gdlr-core-center-align">
                                <div class="gdlr-core-image-item-wrap gdlr-core-media-image gdlr-core-image-item-style-rectangle gdlr-core-image-item-home">
                                    <img src="/assets/customer/images/source/daan-stevens-549933-unsplash-700x430.jpg" alt="" width="700"
                                        height="430" title="ruben-garcia-588365-unsplash" />
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr-home">
                                <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-home">
                                    <?=$this->translate('Thiết kế nột thất')?>
                                </span>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align py-0">
                                <div class="gdlr-core-text-box-item-content text-transform-none">
                                    <p>
                                        <?=$this->translate('Xin chào quý vị và các bạn, chúng tôi xin chân thành cảm ơn quý vị đã đến tham dự chương trình của chúng tôi.')?>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-button-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align">
                                <a class="gdlr-core-button gdlr-core-button-transparent gdlr-core-button-no-border gdlr-core-button-service"
                                    href="#">
                                    <span class="gdlr-core-content"><?=$this->translate('Xem thêm')?></span>
                                    <i class="gdlr-core-pos-right gdlr-core-pos-right-color-main fa fa-long-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-element">
                <div class="gdlr-core-button-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align py-0">
                    <a class="gdlr-core-button  gdlr-core-button-transparent gdlr-core-button-with-border gdlr-core-button-with-border-custom " 
                        href="<?= $this->zfUrl('portfolio')?>">
                        <span class="gdlr-core-content" style="color: #9a827d ;">Xem tất cả</span>
                        <i class="gdlr-core-pos-right fa fa-long-arrow-right" style="color: #9a827d ;"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>