<div class="gdlr-core-pbf-wrapper-content">
    <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-pbf-wrapper-full-no-space">
        <div class="gdlr-core-pbf-element">
            <div class="gdlr-core-revolution-slider-item gdlr-core-item-pdlr">
                <div class="slider-hero">
                    <div class="featured-carousel owl-carousel">
                        <div class="item">
                            <div class="work">
                                <div class="img d-flex align-items-center justify-content-center"
                                    style="background-image: url(assets/customer/images/source/slider-1.jpg);">
                                    <div class="text text-center">
                                        <h2 class="title-slide">Discover New Places</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="work">
                                <div class="img d-flex align-items-center justify-content-center"
                                    style="background-image: url(assets/customer/images/source/slider-2.jpg);">
                                    <div class="text text-center">
                                        <h2 class="title-slide">Dream Destination</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="work">
                                <div class="img d-flex align-items-center justify-content-center"
                                    style="background-image: url(assets/customer/images/source/slider-3.jpg);">
                                    <div class="text text-center">
                                        <h2 class="title-slide">Travel Exploration</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <ul class="thumbnail">
                            <li class="active img"><a href="javascript:void(0);"><img
                                        src="assets/customer/images/source/thumb-1.jpg" alt="Image"
                                        class="img-fluid"></a></li>
                            <li><a href="javascript:void(0);"><img src="assets/customer/images/source/thumb-2.jpg"
                                        alt="Image" class="img-fluid"></a></li>
                            <li><a href="javascript:void(0);"><img src="assets/customer/images/source/thumb-3.jpg"
                                        alt="Image" class="img-fluid"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>