<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-feedback" id="gdlr-core-wrapper-4">
    <div class="gdlr-core-pbf-background-wrap">
        <div class="gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js gdlr-core-img-background "
            style="background-image: url(/assets/customer/images/source/image-bg-5.jpg);"
            data-parallax-speed="0.2"></div>
    </div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container-custom gdlr-core-container-custom-width">
            <div class="gdlr-core-pbf-element">
                <div class="gdlr-core-testimonial-item gdlr-core-item-pdb clearfix gdlr-core-testimonial-style-center gdlr-core-item-pdlr">
                    <div class="gdlr-core-flexslider flexslider gdlr-core-js-2 gdlr-core-nav-style-middle-large"
                        data-type="carousel" data-column="1" data-move="1" data-nav="bullet" data-vcenter-nav="1"
                        data-disable-autoslide="1">
                        <div class="gdlr-core-block-item-title-wrap  gdlr-core-center-align gdlr-core-item-mglr mb-5">
                            <div class="gdlr-core-block-item-title-inner">
                                <h3 class="gdlr-core-block-item-title gdlr-core-block-item-title-feedback">
                                    <?= $this->translate('Đánh giá của khách hàng')?>
                                </h3>
                            </div>
                            <div class="gdlr-core-flexslider-nav gdlr-core-round-style gdlr-core-absolute-center gdlr-core-right">
                            </div>
                        </div>
                        <ul class="slides">
                            <li class="gdlr-core-item-mglr">
                                <div class="gdlr-core-testimonial clearfix">
                                    <div class="gdlr-core-testimonial-content-wrap">
                                        <div class="gdlr-core-testimonial-quote gdlr-core-quote-font gdlr-core-skin-icon text-white">&#8220;</div>
                                        <div class="gdlr-core-testimonial-content gdlr-core-info-font gdlr-core-skin-content text-white fs-5">
                                            <p><?= $this->translate('Một sự thanh thản tuyệt vời chiếm hữu toàn bộ tâm hồn tôi, 
                                            giống như những buổi sáng ngọt ngào của mùa xuân mà tôi tận hưởng bằng cả trái tim mình. 
                                            Tôi chỉ có một mình và cảm thấy sự quyến rũ của sự tồn tại ở nơi này, nơi được tạo ra để mang 
                                            lại niềm hạnh phúc cho những linh hồn như tôi. Tôi rất hạnh phúc, bạn thân mến, 
                                            quá đắm chìm trong ý nghĩa tinh tế của tôi.')?></p>
                                        </div>
                                        <div class="gdlr-core-testimonial-author-wrap clearfix">
                                            <div class="gdlr-core-testimonial-author-image gdlr-core-media-image">
                                                <img src="/assets/customer/images/source/personnel-2-2-150x150.jpg" alt="" width="150"
                                                    height="150" title="personnel-2-2" /></div>
                                            <div class="gdlr-core-testimonial-author-content">
                                                <div class="gdlr-core-testimonial-title gdlr-core-title-font gdlr-core-skin-title text-white">
                                                    Nguyễn Hoà
                                                </div>
                                                <div class="gdlr-core-testimonial-position gdlr-core-info-font gdlr-core-skin-caption text-white">
                                                    CEO, InDesign
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>