<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-expertise">
    <div class="gdlr-core-pbf-background-wrap">
        <div class="gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js gdlr-core-img-background"
             data-parallax-speed="0.2">
        </div>
    </div>
    <div class="gdlr-core-wrapper-bg-overlay gdlr-core-pos-right gdlr-core-pos-right-expertise"
        style="background-image: url(/assets/customer/images/source/shutterstock_543421996.jpg);">
    </div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-column gdlr-core-column-30 gdlr-core-column-first">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-margin-expertise">
                    <div class="gdlr-core-pbf-background-wrap gdlr-core-pbf-background-wrap-expertise">
                    </div>
                    <?php echo $this->partial('partial/item-expertise.phtml')?>
                </div>
            </div>
        </div>
    </div>
</div>