<?php 
$teams = [
    [
        'name' => 'John Balmer',
        'position' => 'CEO & Founder',
        'src' => '/assets/customer/images/source/personnel-1-1.jpg',
        'url_facebook' => 'https://www.facebook.com',
        'url_linkedin' => 'https://www.linkedin.com',
        'url_twitter' => 'https://twitter.com',
    ],
    [
        'name' => 'Marry Scott',
        'position' => 'Planning Manager',
        'src' => '/assets/customer/images/source/personnel-2-1.jpg',
        'url_facebook' => 'https://www.facebook.com',
        'url_linkedin' => 'https://www.linkedin.com',
        'url_twitter' => 'https://twitter.com',
    ],
    [
        'name' => 'Jennette Jones',
        'position' => 'Senior Interior',
        'src' => '/assets/customer/images/source/personnel-3-1.jpg',
        'url_facebook' => 'https://www.facebook.com',
        'url_linkedin' => 'https://www.linkedin.com',
        'url_twitter' => 'https://twitter.com',
    ],
    [
        'name' => 'Joseph Smith',
        'position' => 'Project Manager',
        'src' => '/assets/customer/images/source/personnel-4-1.jpg',
        'url_facebook' => 'https://www.facebook.com',
        'url_linkedin' => 'https://www.linkedin.com',
        'url_twitter' => 'https://twitter.com',
    ]
]
?>
<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-team">
    <div class="gdlr-core-pbf-background-wrap"></div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-column gdlr-core-column-30 gdlr-core-column-first">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-1">
                                <div class="gdlr-core-title-item-title-wrap  gdlr-core-with-divider">
                                    <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-team">
                                        <?= $this->translate('Đội ngũ công ty')?>
                                    </h3>
                                    <div class="gdlr-core-title-item-divider gdlr-core-right gdlr-core-skin-divider gdlr-core-skin-divider-team"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-30">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align">
                                <div class="gdlr-core-text-box-item-content gdlr-core-text-box-item-content-team">
                                    <p>
                                        <?= $this->translate('Một sự thanh thản tuyệt vời chiếm hữu toàn bộ tâm hồn tôi, 
                                        giống như những buổi sáng ngọt ngào của mùa xuân mà tôi tận hưởng bằng cả trái tim mình. 
                                        Tôi chỉ có một mình và cảm thấy sự quyến rũ của sự tồn tại ở nơi này, nơi được tạo ra để mang 
                                        lại niềm hạnh phúc cho những linh hồn như tôi. Tôi rất hạnh phúc, bạn thân mến, quá đắm chìm trong 
                                        cảm giác tinh tế của sự tồn tại đơn thuần yên tĩnh, đến nỗi tôi bỏ bê tài năng của mình. 
                                        Tôi không thể vẽ một nét nào vào thời điểm hiện tại; nhưng tôi cảm thấy rằng tôi chưa bao giờ là một người vĩ đại hơn.')?>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-team-bg">
    <div class="gdlr-core-pbf-background-wrap"></div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-element">
                <div class="gdlr-core-item-pdlr">
                    <div class="gdlr-core-personnel-item gdlr-core-item-pdb clearfix gdlr-core-left-align 
                        gdlr-core-personnel-item-style-grid gdlr-core-personnel-style-grid gdlr-core-with-divider swiper"
                        id="teams-swiper">
                        <div class="swiper-wrapper">
                            <?php foreach ($teams as $k => $item):?>
                            <div class="swiper-slide">
                                <div class="gdlr-core-personnel-list clearfix">
                                    <div class="gdlr-core-personnel-list-image gdlr-core-media-image  gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                        <img src="<?= $item['src']?>" alt="<?= $item['name']?>" width="600" height="718"
                                            title="<?= $item['name']?>" />
                                    </div>
                                    <div class="gdlr-core-personnel-list-content-wrap">
                                        <h3 class="gdlr-core-personnel-list-title gdlr-core-personnel-list-title-team">
                                            <a href="javascript:void(0);"><?= $item['name']?></a>
                                        </h3>
                                        <div class="gdlr-core-personnel-list-position gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-team">
                                            <?= $item['position']?>
                                        </div>
                                        <div class="gdlr-core-personnel-list-divider gdlr-core-skin-divider"></div>
                                        <div class="gdlr-core-personnel-list-social">
                                            <div class="gdlr-core-social-network-item gdlr-core-item-pdb  gdlr-core-none-align py-0">
                                                <?php if (!empty($item['url_facebook'])):?>
                                                <a href="<?= $item['url_facebook']?>" target="_blank" class="gdlr-core-social-network-icon" title="facebook">
                                                    <i class="fa fa-facebook"></i>
                                                </a><?php 
                                                endif; 
                                                if (!empty($item['url_linkedin'])):?>
                                                <a href="<?= $item['url_linkedin']?>" target="_blank" class="gdlr-core-social-network-icon" title="linkedin">
                                                    <i class="fa fa-linkedin"></i>
                                                </a><?php 
                                                endif; 
                                                if (!empty($item['url_twitter'])):?>
                                                <a href="<?= $item['url_twitter']?>" target="_blank" class="gdlr-core-social-network-icon" title="twitter">
                                                    <i class="fa fa-twitter"></i>
                                                </a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        </div>
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>