<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-report">
    <div class="gdlr-core-pbf-background-wrap"></div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js " data-gdlr-animation="fadeInUp"
        data-gdlr-animation-duration="600ms" data-gdlr-animation-offset="0.8">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-column gdlr-core-column-15 gdlr-core-column-first">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-counter-item gdlr-core-item-pdlr gdlr-core-item-pdb ">
                                <div class="gdlr-core-counter-item-number gdlr-core-skin-title gdlr-core-title-font gdlr-core-title-font-report">
                                    <span class="gdlr-core-counter-item-count gdlr-core-js" data-duration="4000"
                                        data-counter-start="0" data-counter-end="345">0</span>
                                    </div>
                                <div class="gdlr-core-counter-item-bottom-text gdlr-core-skin-content gdlr-core-skin-content-report">
                                    <?= $this->translate('Dự án')?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-15">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-counter-item gdlr-core-item-pdlr gdlr-core-item-pdb ">
                                <div class="gdlr-core-counter-item-number gdlr-core-skin-title gdlr-core-title-font gdlr-core-title-font-report">
                                    <span class="gdlr-core-counter-item-count gdlr-core-js" data-duration="4000"
                                        data-counter-start="0" data-counter-end="934">0</span>
                                </div>
                                <div class="gdlr-core-counter-item-bottom-text gdlr-core-skin-content gdlr-core-skin-content-report">
                                    <?= $this->translate('Khách hàng')?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-15">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-counter-item gdlr-core-item-pdlr gdlr-core-item-pdb ">
                                <div class="gdlr-core-counter-item-number gdlr-core-skin-title gdlr-core-title-font gdlr-core-title-font-report">
                                    <span class="gdlr-core-counter-item-count gdlr-core-js" data-duration="4000"
                                        data-counter-start="0" data-counter-end="20">0</span>
                                    <span class="gdlr-core-counter-item-suffix">+</span>
                                </div>
                                <div class="gdlr-core-counter-item-bottom-text gdlr-core-skin-content gdlr-core-skin-content-report">
                                    <?= $this->translate('Kinh nghiệm')?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-15">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-counter-item gdlr-core-item-pdlr gdlr-core-item-pdb ">
                                <div class="gdlr-core-counter-item-number gdlr-core-skin-title gdlr-core-title-font gdlr-core-title-font-report">
                                    <span class="gdlr-core-counter-item-count gdlr-core-js" data-duration="4000"
                                        data-counter-start="0" data-counter-end="16">0</span>
                                </div>
                                <div class="gdlr-core-counter-item-bottom-text gdlr-core-skin-content gdlr-core-skin-content-report">
                                    <?= $this->translate('Giải thưởng')?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>