<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-legacy" id="gdlr-core-wrapper-6">
    <div class="gdlr-core-pbf-background-wrap"></div>
    <div class="gdlr-core-wrapper-bg-overlay gdlr-core-pos-left gdlr-core-pos-right-expertise"
        style="background-image: url(/assets/customer/images/source/shutterstock_549055441.jpg);">
    </div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-column gdlr-core-column-30 gdlr-core-column-first">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "></div>
                </div>
            </div>
            <div class="gdlr-core-pbf-column gdlr-core-column-30">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-legacy">
                    <div class="gdlr-core-pbf-background-wrap gdlr-core-pbf-background-wrap-expertise">
                    </div>
                    <?php echo $this->partial('partial/item-legacy.phtml')?>
                </div>
            </div>
        </div>
    </div>
</div>