<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-story" id="gdlr-core-wrapper-1">
    <div class="gdlr-core-pbf-background-wrap">
        <div class="gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js gdlr-core-pbf-background-home"
            style="background-image: url(/assets/customer/images/source/hp1-about-bg-2.jpg);"
            data-parallax-speed="0.1">
        </div>
    </div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js " data-gdlr-animation="fadeInDown"
        data-gdlr-animation-duration="600ms" data-gdlr-animation-offset="0.8">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
            <div class="gdlr-core-pbf-column gdlr-core-column-60 gdlr-core-column-first" id="gdlr-core-column-1">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-home">
                    <div class="gdlr-core-pbf-background-wrap gdlr-core-pbf-background-wrap-home"></div>
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr py-4">
                                <div class="gdlr-core-title-item-left-image gdlr-core-media-image">
                                    <img src="/assets/customer/images/source/hp-1home-icon.png" alt="Icon home" width="58" height="58"
                                        title="Icon home" />
                                </div>
                                <div class="gdlr-core-title-item-left-image-wrap">
                                    <div class="gdlr-core-title-item-title-wrap ">
                                        <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-story">
                                            <?=$this->translate('Giới thiệu')?>
                                        </h3>
                                    </div>
                                    <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-story">
                                        <?=$this->translate('Chúng tôi là ai')?>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align py-1">
                                <div class="gdlr-core-text-box-item-content text-transform-none">
                                    <?php echo $this->partial('partial/item-our-story.phtml')?>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-button-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align">
                                <a class="gdlr-core-button gdlr-core-button-transparent gdlr-core-button-with-border gdlr-core-button-story"
                                    href="<?= $this->zfUrl('about')?>">
                                    <span class="gdlr-core-content"><?=$this->translate('Xem thêm')?></span>
                                    <i class="gdlr-core-pos-right fa fa-long-arrow-right gdlr-core-pos-right-color-main fs-1">
                                    </i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>