<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-service-bg" id="gdlr-core-wrapper-5">
    <div class="gdlr-core-pbf-background-wrap">
        <div class="gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js dlr-core-img-background"
            style="background-image: url(/assets/customer/images/source/hp1-service-bg.jpg)"
            data-parallax-speed="0.3"></div>
    </div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container"></div>
    </div>
</div>
<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-service">
    <div class="gdlr-core-pbf-background-wrap"></div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js " data-gdlr-animation="fadeInUp"
        data-gdlr-animation-duration="600ms" data-gdlr-animation-offset="0.8">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container-custom max-width-1280">
            <?php foreach([
                'Thiết kế hoàn hảo', 'Kế hoạch cẩn thận', 'Thực hiện thông minh'
            ] as $k => $item): ?>
            <div class="gdlr-core-pbf-column gdlr-core-column-20 <?= $k == 0 ? 'gdlr-core-column-first' : ''?>" id="gdlr-core-column-<?=$k + 5?>">
                <div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-service"
                    data-sync-height="service-3-height">
                    <div class="gdlr-core-pbf-background-wrap gdlr-core-pbf-background-wrap-service">
                    </div>
                    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js  gdlr-core-sync-height-content">
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-1">
                                <div class="gdlr-core-title-item-title-wrap ">
                                    <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-service">
                                        <?= $this->translate($item);?>
                                    </h3>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align my-3">
                                <div class="gdlr-core-divider-container max-width-140">
                                    <div class="gdlr-core-divider-line gdlr-core-skin-divider gdlr-core-skin-divider-service"></div>
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-element">
                            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align py-0">
                                <div class="gdlr-core-text-box-item-content gdlr-core-text-box-item-content-service">
                                    <p><?= $this->translate('Một sự thanh thản tuyệt vời đã xâm chiếm toàn bộ tâm hồn tôi, giống như những buổi sáng ngọt ngào của mùa xuân.')?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>