<div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "
    data-gdlr-animation="fadeInRight" data-gdlr-animation-duration="600ms"
    data-gdlr-animation-offset="0.8">
    <div class="gdlr-core-pbf-element">
        <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr">
            <span class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption gdlr-core-skin-caption-about-expertise">
                <?= $this->translate('Dịch vụ')?>
            </span>
            <div class="gdlr-core-title-item-title-wrap ">
                <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-expertise">
                    <?= $this->translate('của chúng tôi')?>
                </h3>
            </div>
        </div>
    </div>
    <div class="gdlr-core-pbf-element">
        <div
            class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align">
            <div class="gdlr-core-text-box-item-content text-transform-none">
                <p>Dịch vụ Thiết kế kết cấu bao gồm lập kế hoạch không gian, bản vẽ thiết kế, 
                    lựa chọn, điều phối dự án và tạo kiểu. Có hàng trăm quyết định để thực hiện 
                    và chi tiết để xem xét khi lập kế hoạch thiết kế nhà của bạn. Làm sai có thể 
                    khiến bạn tốn rất nhiều thời gian và tiền bạc. Textured Designs đã được bắt 
                    đầu để giúp bạn đạt được tầm nhìn của mình một cách tự tin và dễ dàng. 
                    Chúng tôi làm việc không mệt mỏi để đảm bảo dự án nhà của bạn được hoàn thành 
                    trên cả mong đợi của bạn.</p>
            </div>
        </div>
    </div>
</div>