<div class="gdlr-core-pbf-wrapper gdlr-core-pbf-wrapper-slide-about">
    <div class="gdlr-core-pbf-background-wrap"></div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-pbf-wrapper-full-no-space">
            <div class="gdlr-core-pbf-element">
                <div class="gdlr-core-gallery-item gdlr-core-item-pdb clearfix  gdlr-core-gallery-item-style-grid-no-space gdlr-core-item-pdlr p-0">
                    <div class="gdlr-core-gallery-item-holder gdlr-core-js-2 clearfix swiper"
                        id="<?= $idElement?>">
                        <div class="swiper-wrapper">
                            <?php foreach ($slides as $k => $item):?>
                                <div class="swiper-slide">
                                    <div class="gdlr-core-item-list gdlr-core-gallery-column <?= $k == 0 ? 'gdlr-core-column-first' : ''?>">
                                        <div class="gdlr-core-gallery-list gdlr-core-media-image">
                                            <a class="gdlr-core-lightgallery gdlr-core-js "
                                                href="<?= $item['src']?>"
                                                data-lightbox-group="gdlr-core-img-group-1">
                                                <img src="<?= str_replace('.', '-' . implode('x', $item['size']) . '.', $item['src'])?>" 
                                                    alt="<?= $item['name']?>" title="<?= $item['name']?>" 
                                                    width="<?=$item['size'][0]?>" height="<?=$item['size'][1]?>" />
                                                <span class="gdlr-core-image-overlay ">
                                                    <i class="gdlr-core-image-overlay-icon gdlr-core-size-22 fa fa-search"></i>
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>