<div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "
    data-gdlr-animation="fadeInLeft" data-gdlr-animation-duration="600ms"
    data-gdlr-animation-offset="0.8">
    <div class="gdlr-core-pbf-element">
        <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr">
            <div class="gdlr-core-title-item-title-wrap ">
                <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-expertise">
                    <?= $this->translate('Hầu hết dự án bao gồm')?>
                </h3>
            </div>
        </div>
    </div>
    <div class="gdlr-core-pbf-element">
        <div class="gdlr-core-skill-bar-item gdlr-core-item-pdlr gdlr-core-item-pdb  gdlr-core-size-small gdlr-core-type-round">
            <div class="gdlr-core-skill-bar">
                <div class="gdlr-core-skill-bar-head gdlr-core-title-font">
                    <span class="gdlr-core-skill-bar-title"><?= $this->translate('Interior Design');?></span>
                    <span class="gdlr-core-skill-bar-right">85%</span>
                </div>
                <div class="gdlr-core-skill-bar-progress">
                    <div class="gdlr-core-skill-bar-filled gdlr-core-js" data-width="85"></div>
                </div>
            </div>
            <div class="gdlr-core-skill-bar">
                <div class="gdlr-core-skill-bar-head gdlr-core-title-font">
                    <span class="gdlr-core-skill-bar-title"><?= $this->translate('AutoCAD');?></span>
                    <span class="gdlr-core-skill-bar-right">75%</span>
                </div>
                <div class="gdlr-core-skill-bar-progress">
                    <div class="gdlr-core-skill-bar-filled gdlr-core-js" data-width="75"></div>
                </div>
            </div>
            <div class="gdlr-core-skill-bar">
                <div class="gdlr-core-skill-bar-head gdlr-core-title-font">
                    <span class="gdlr-core-skill-bar-title"><?= $this->translate('Lighting');?></span>
                    <span class="gdlr-core-skill-bar-right">95%</span>
                </div>
                <div class="gdlr-core-skill-bar-progress">
                    <div class="gdlr-core-skill-bar-filled gdlr-core-js" data-width="95"></div>
                </div>
            </div>
            <div class="gdlr-core-skill-bar">
                <div class="gdlr-core-skill-bar-head gdlr-core-title-font">
                    <span class="gdlr-core-skill-bar-title"><?= $this->translate('3D Skills');?></span>
                    <span class="gdlr-core-skill-bar-right">85%</span>
                </div>
                <div class="gdlr-core-skill-bar-progress">
                    <div class="gdlr-core-skill-bar-filled gdlr-core-js" data-width="85"></div>
                </div>
            </div>
        </div>
    </div>
</div>