<div class="gdlr-core-pbf-column-content-margin gdlr-core-js gdlr-core-pbf-column-content-service"
    data-sync-height="service-3-height">
    <div class="gdlr-core-pbf-background-wrap gdlr-core-pbf-background-wrap-service">
    </div>
    <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js  gdlr-core-sync-height-content">
        <div class="gdlr-core-pbf-element">
            <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr py-1">
                <div class="gdlr-core-title-item-title-wrap ">
                    <h3 class="gdlr-core-title-item-title gdlr-core-skin-title gdlr-core-skin-title-service">
                        <?= $this->translate($item);?>
                    </h3>
                </div>
            </div>
        </div>
        <div class="gdlr-core-pbf-element">
            <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align my-3">
                <div class="gdlr-core-divider-container max-width-140">
                    <div class="gdlr-core-divider-line gdlr-core-skin-divider gdlr-core-skin-divider-service"></div>
                </div>
            </div>
        </div>
        <div class="gdlr-core-pbf-element">
            <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align py-0">
                <div class="gdlr-core-text-box-item-content gdlr-core-text-box-item-content-service">
                    <p><?= $this->translate('Một sự thanh thản tuyệt vời đã xâm chiếm toàn bộ tâm hồn tôi, giống như những buổi sáng ngọt ngào của mùa xuân.')?></p>
                </div>
            </div>
        </div>
    </div>
</div>
