<?php
use Laminas\Mvc\Application;

$this->layout('layout/login');
$reasonMessage = 'The requested URL could not be matched by routing.';
?>
<?php if (! empty($this->reason)) {

    switch ($this->reason) {
        case Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
            $reasonMessage = 'The requested controller was unable to dispatch the request.';
            break;
        case Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
            $reasonMessage = 'The requested middleware was unable to dispatch the request.';
            break;
        case Application::ERROR_CONTROLLER_NOT_FOUND:
            $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
            break;
        case Application::ERROR_CONTROLLER_INVALID:
            $reasonMessage = 'The requested controller was not dispatchable.';
            break;
        case Application::ERROR_ROUTER_NO_MATCH:
            $reasonMessage = 'The requested URL could not be matched by routing.';
            break;
        default:
            $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
            break;
    }
}
?>
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg mt-0">
    <div class="page-header align-items-start min-vh-100"
    style="background-image: url('/assets/manager/images/bg-404-error.jpg');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-12 m-auto text-center">
                    <h1 class="display-1 text-bolder text-white">Error 404</h1>
                    <h2 class="text-white"><?=$this->translate($this->message);?></h2>
                    <p class="lead text-white"><?=$this->translate($reasonMessage);?></p>
                    <button type="button" class="btn btn-outline-white mt-4"
                        onClick="document.location.href = '<?= $this->zfUrl('home', ['action' => 'index']) ?>';"
                    >
                        <?=$this->translate('Về trang chủ');?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</main>
