<?php

$this->headTitle($pageTitle);

$this->menuLeft()->setActiveItemId($activeItemId);
$this->bootstrapToolbar([
    $this->toolbarClose($this->zfUrl('home'))
]);

$this->pageBreadcrumbs()->setItems([
    $this->translate('Trang chủ') => $this->zfUrl('home'),
    $pageTitle => $this->zfUrl($routeName),
]);

$this->headScriptAction(null, [], [
    'action' => 'add',
    'controller' => 'service',
    'module' => 'manager'
]);
?>
<div class="row mb-5">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h5><?= $this->translate($pageTitle) ?></h5>
            </div>
            <div class="card-body pt-0">
                <form method="POST" id="frmService">
                    <div class="avatar avatar-xl">
                        <label class="form-label">
                            <?= $this->translate('Icon') ?>
                        </label>
                        <input type="file" accept="image/*" name="icon" id="icon" class="form-control" autocomplete="off">
                    </div>
                    <div class="input-group input-group-outline mt-4">
                        <label class="form-label">
                            <?= $this->translate('Tiêu đề') ?>
                        </label>
                        <input type="text" name="title" id="title" class="form-control" autocomplete="off">
                    </div>
                    <div class="input-group input-group-outline my-4">
                        <label class="form-label">
                            <?= $this->translate('') ?>
                        </label>
                        <textarea name="description" id="description" class="form-control"></textarea>
                    </div>
                    <div class="input-group input-group-outline my-4">
                        <label class="form-label">
                            <?= $this->translate('Trạng thái') ?>
                        </label>
                        <div class="form-check form-switch mb-0">
                            <input class="form-check-input" checked type="checkbox" name="status" id="status">
                        </div>
                    </div>
                    <button type="submit"
                        title="<?=$this->translate('Lưu')?>"
                        class="btn bg-gradient-dark btn-sm text-center mb-0 mt-6">
                        <span class="txt-btn"><?= $this->translate('Lưu') ?></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>