<?php
$this->headTitle($pageTitle);
$this->menuLeft()->setActiveItemId($activeItemId);
$this->bootstrapToolbar([
    $this->toolbarInsert($this->zfUrl($routeName, ['action'=>'add'])),
    $this->toolbarDelete($this->zfUrl($routeName, ['action'=>'delete'])),
]);

$this->pageBreadcrumbs()->setItems([
    $this->translate('Trang chủ') => $this->zfUrl('home'),
    $pageTitle => $this->zfUrl($routeName),
]);

$this->headScriptAction(null, [], [
    'action' => 'index',
    'controller' => 'index',
    'module' => 'project'
]);
$this->headStyleAction(null, [], [
    'action' => 'index', 'controller' => 'index', 'module' => 'project'
]);
?>
<div class="row">
    <div class="col-12">
        <form id="adminForm" method="get" enctype="application/x-www-form-urlencoded">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-lg-flex">
                        <div>
                            <h5 class="mb-0"><?= $pageTitle?></h5>
                            <!-- <p class="text-sm mb-0">
                                Showing 1 to 7 of 15 entries
                            </p> -->
                        </div>
                        <div class="ms-auto my-auto mt-lg-0 mt-2">
                            <div class="ms-auto my-auto">
                                <button class="btn btn-icon btn-outline-primary btn-sm mb-0" type="button">
                                    <i class="material-icons text-xs position-relative">archive</i>
                                    Export
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="input-group input-group-outline mt-3">
                                <label class="form-label">Search</label>
                                <input type="text" name="keyword" class="form-control" autocomplete="off">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="select mt-3">
                                <select class="form-control px-3" name="category"
                                    id="category">
                                    <option value="Choice 1" selected="">Clothing</option>
                                    <option value="Choice 2">Real Estate</option>
                                    <option value="Choice 3">Electronics</option>
                                    <option value="Choice 4">Furniture</option>
                                    <option value="Choice 5">Others</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <button class="btn btn-icon bg-gradient-primary btn-md mt-3 mb-0 px-3" type="submit">
                                <i class="material-icons text-md position-relative">search</i>
                                <?= $this->translate('Tìm kiếm');?>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body px-0 pb-0">
                    <div class="d-lg-flex ps-4">
                        <p class="text-sm mb-0">
                            Showing 1 to 7 of 15 entries
                        </p>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="w-2 text-center fs-6">
                                        <?= $this->manageCheckboxAll();?>
                                    </th>
                                    <th class="text-dark text-xs text-secondary text-uppercase opacity-7">
                                        Manager
                                    </th>
                                    <th class="text-dark text-xs text-center text-secondary text-uppercase opacity-7">
                                        Manager
                                    </th>
                                    <th class="text-dark text-xs text-center text-secondary text-uppercase opacity-7">
                                        Manager
                                    </th>
                                    <th class="text-dark text-xs text-center text-secondary text-uppercase opacity-7">
                                        Manager
                                    </th>
                                    <th class="text-dark text-xs text-center text-secondary text-uppercase opacity-7">
                                        Manager
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach (range(1, 15) as $no => $item): ?>
                                    <tr>
                                        <td class="text-center fs-6">
                                            <?= $this->manageCheckbox($no)?>
                                        </td>
                                        <td>
                                            <div class="d-flex px-2 py-1">
                                                <div>
                                                    <img src="https://demos.creative-tim.com/test/material-dashboard-pro/assets/img/team-2.jpg"
                                                        class="avatar avatar-sm me-3">
                                                </div>
                                                <div class="d-flex flex-column justify-content-center">
                                                    <h6 class="mb-0 text-xs">John Michael</h6>
                                                    <p class="text-xs text-secondary mb-0">john@creative-tim.com</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <p class="text-xs font-weight-bold mb-0">Manager</p>
                                            <p class="text-xs text-secondary mb-0">Organization</p>
                                        </td>
                                        <td class="align-middle text-center text-sm">
                                            <span class="badge badge-sm badge-success">Online</span>
                                        </td>
                                        <td class="align-middle text-center">
                                            <span class="text-secondary text-xs font-weight-normal">23/04/18</span>
                                        </td>
                                        <td class="text-sm text-center"><?php
                                            echo  $this->manageUpdate(
                                                $this->zfUrl($routeName, ['action'=>'edit', 'id'=> $no])
                                            );
                                            echo  $this->manageDetail(
                                                $this->zfUrl($routeName, ['action'=>'detail', 'id'=> $no])
                                            );
                                            echo  $this->manageDelete($this->zfUrl($routeName, 
                                                ['action'=>'delete', 'id'=> $no ])
                                            );
                                        ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            
                <div class="card-footer">
                    <nav aria-label="Page navigation example">
                        <div class="d-flex justify-content-center">
                            <div class="dropdown page-item">
                                <button class="btn dropdown-toggle page-link" type="button"           
                                    id="numberEntry" data-bs-toggle="dropdown" aria-expanded="false">
                                    30
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="numberEntry">
                                    <li><a class="dropdown-item" href="#">30</a></li>
                                    <li><a class="dropdown-item" href="#">60</a></li>
                                    <li><a class="dropdown-item" href="#">90</a></li>
                                </ul>
                            </div>
                            <ul class="pagination">
                                <li class="page-item disabled">
                                    <a class="page-link" href="javascript:;" tabindex="-1">
                                        <span class="material-icons">keyboard_arrow_left</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link" href="javascript:;">1</a></li>
                                <li class="page-item active"><a class="page-link" href="javascript:;">2</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:;">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript:;">
                                        <span class="material-icons">
                                            keyboard_arrow_right
                                        </span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </form>
    </div>
</div>