<?php
use Laminas\Form\Element;
use Models\Entities\Admin;
use Models\Utilities\User;

$this->headTitle($pageTitle);
$this->menuLeft()->setActiveItemId($activeItemId);
$this->bootstrapToolbar([
    $this->toolbarSave(null, null, ['onclick' => '', 'aclass' => 'btn-save']),
    $this->toolbarClose($this->zfUrl('admin-user'))
]);

$this->pageBreadcrumbs()->setItems([
    $this->translate('Trang chủ') => $this->zfUrl('home'),
    $pageTitle => $this->zfUrl($routeName),
]);

$this->headScriptAction(null, [
    
], [
    'action' => 'add',
    'controller' => 'admin',
    'module' => 'manager'
]);

$imgNameDefaultBg = '/assets/manager/images/bg-timeline.jpeg';
if (!empty($user) && $user->adm_bg_timeline) {
    $imgPath = Admin::getImgPath();
    $srcImgBg = str_replace('__id__', $user->adm_code, $imgPath)
        . $user->adm_bg_timeline;
    if (!file_exists(PUBLIC_PATH.$srcImgBg)) {
        $srcImgBg = $imgNameDefaultBg;
    }
} else {
    $srcImgBg = $imgNameDefaultBg;
}
?>
<div class="row">
    <div class="col-12">
        <form id="adminForm" name="adminForm" enctype="multipart/form-data" method="POST">
            <input type="hidden" id="type-form" value="<?=$isEdit?>">
            <div class="page-header min-height-300 border-radius-xl mx-n2" id="block-bg-timeline"
                style="background-image: url('<?=$srcImgBg?>');">
                <span class="bg-gradient-primary opacity-6"></span>
                <a href="javascript:;" id="update-bg-timeline" 
                    title="<?=$this->translate($transBg = $isEdit ? 'Chỉnh sửa ảnh bìa' : 'Thêm ảnh bìa')?>"
                    class="btn btn-sm btn-icon-only p-02 bg-gradient-primary position-absolute top-2 end-2 mb-n2 me-n2">
                    <span class="material-icons text-xs top-0 mt-n2 icon-edit-bg-timeline" data-bs-toggle="tooltip" 
                        data-bs-placement="top" title="" aria-hidden="true" 
                        data-bs-original-title="<?=$this->translate($transBg)?>" 
                        aria-label="<?=$this->translate($transBg)?>">
                        edit
                    </span>
                    <span class="spinner-border spinner-border-sm text-light text-xs" role="status" aria-hidden="true"></span>
                    <span class="visually-hidden">Loading...</span>
                </a>
                <input type="file" name="bg-timeline" accept="image/*" class="d-none" id="bg-timeline-input">
            </div>
            <div class="card card-body mt-n5 mx-1" id="profile">
                <div class="row justify-content-center align-items-center">
                    <div class="col-sm-auto col-4">
                        <div class="avatar avatar-xl position-relative">
                            <img src="<?=User::getAvatarUser($user)?>" alt="<?= $user->adm_fullname ?? 'Avatar'?>"
                                class="w-100 h-100 object-fit-cover rounded-circle shadow-sm">
                            <a href="javascript:;" id="update-avatar-btn" 
                                title="<?=$this->translate($transAvt = $isEdit ? 'Chỉnh sửa avatar' : 'Thêm avatar')?>"
                                class="btn btn-sm btn-icon-only p-02 bg-gradient-primary position-absolute bottom-0 end-0 mb-n2 me-n2">
                                <span class="material-icons text-xs top-0 mt-n2 icon-edit-avatar" data-bs-toggle="tooltip" 
                                    data-bs-placement="top" title="" aria-hidden="true" 
                                    data-bs-original-title="<?=$this->translate($transAvt)?>" 
                                    aria-label="<?=$this->translate($transAvt)?>">
                                    edit
                                </span>
                                <span class="spinner-border spinner-border-sm text-light text-xs" role="status" aria-hidden="true"></span>
                                <span class="visually-hidden">Loading...</span>
                            </a>
                            <input type="file" name="avatar" accept="image/*" class="d-none" id="avatar-input">
                        </div>
                    </div>
                    <div class="col-sm-auto ms-sm-auto mt-sm-0 mt-3 d-flex">
                        &nbsp;
                    </div>
                </div>
            </div>

            <div class="card mt-4" id="basic-info">
                <div class="card-header">
                    <h5>
                        <?= $this->translate('Thông tin cơ bản') ?>
                    </h5>
                </div>
                <div class="card-body pt-0">
                    <div class="row">
                        <div class="col-6">
                            <div class="input-group input-group-static">
                                <label>
                                    <?= $this->translate('Tên') ?>
                                </label>
                                <input type="text" class="form-control" name="first_name" id="first_name"
                                    placeholder="<?= $this->translate('Ví dụ: Thuỳ Trúc') ?>" 
                                    value="<?=$user->adm_json_name['first'] ?? ''?>">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="input-group input-group-static">
                                <label>
                                    <?= $this->translate('Họ') ?>
                                </label>
                                <input type="text" class="form-control" name="last_name" id="last_name"
                                    placeholder="<?= $this->translate('Ví dụ: Nguyễn Trần') ?>" 
                                    value="<?=$user->adm_json_name['last'] ?? ''?>">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 col-6">
                            <label class="form-label mt-4 ms-0">
                                <?= $this->translate('Giới tính') ?>
                            </label>
                            <?php
                            $select = new Element\Select('gender');
                            $select->setAttributes([
                                'class' => 'form-control choices',
                                'id' => 'gender'
                            ]);
                            $select->setValueOptions([
                                Admin::GENDER_MALE => $this->translate('Nam'),
                                Admin::GENDER_FEMALE => $this->translate('Nữ'),
                                Admin::GENDER_OTHER => $this->translate('Khác'),
                            ]);
                            $select->setValue(htmlspecialchars($user->adm_gender ?? Admin::GENDER_MALE));
                            echo $this->formSelect($select);
                            ?>
                        </div>
                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col-sm-3 col-4">
                                    <label class="form-label mt-4">
                                        <?= $this->translate('Sinh nhật') ?>
                                    </label>
                                    <?php
                                    $years = array_combine(
                                        $ranges = range(date('Y'), 1900),
                                        array_map(function ($item) {
                                            return $item;
                                        }, $ranges)
                                    );
                                    $select = new Element\Select('birthday[year]');
                                    $select->setAttributes([
                                        'class' => 'form-control choices',
                                        'id' => 'birthday_year'
                                    ]);
                                    $select->setValueOptions($years);
                                    $birthdays = $user->adm_birthday ?? 0;
                                    $select->setValue(htmlspecialchars(
                                        !empty($birthdays) ? date('Y', $birthdays) : date('Y')
                                    ));
                                    echo $this->formSelect($select);
                                    ?>
                                </div>
                                <div class="col-sm-5 col-5">
                                    <label class="form-label mt-4 ms-0">&nbsp;</label>
                                    <?php
                                    $months = [
                                        1 => $this->translate('Tháng 1'),
                                        2 => $this->translate('Tháng 2'),
                                        3 => $this->translate('Tháng 3'),
                                        4 => $this->translate('Tháng 4'),
                                        5 => $this->translate('Tháng 5'),
                                        6 => $this->translate('Tháng 6'),
                                        7 => $this->translate('Tháng 7'),
                                        8 => $this->translate('Tháng 8'),
                                        9 => $this->translate('Tháng 9'),
                                        10 => $this->translate('Tháng 10'),
                                        11 => $this->translate('Tháng 11'),
                                        12 => $this->translate('Tháng 12'),
                                    ];
                                    $select = new Element\Select('birthday[month]');
                                    $select->setAttributes([
                                        'class' => 'form-control choices',
                                        'id' => 'birthday_month'
                                    ]);
                                    $select->setValueOptions($months);
                                    $select->setValue(htmlspecialchars(
                                        !empty($birthdays) ? date('n', $birthdays) : date('n')
                                    ));
                                    echo $this->formSelect($select);
                                    ?>
                                </div>
                                <div class="col-sm-4 col-3">
                                    <label class="form-label mt-4 ms-0">&nbsp;</label>
                                    <select class="form-control" name="birthday[day]" id="birthday_day" 
                                        data-value="<?=!empty($birthdays) ? date('j', $birthdays) : date('j')?>">
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-6">
                            <div class="input-group input-group-static">
                                <label>Email</label>
                                <input type="email" class="form-control" name="email" id="email"
                                    placeholder="<?=$this->translate('Ví dụ: example@email.com')?>"
                                    value="<?=$user->adm_email ?? ''?>">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="input-group input-group-static">
                                <label>
                                    <?= $this->translate('Xác nhận email') ?>
                                </label>
                                <input type="email" class="form-control" id="confirm_email" name="confirm_email"
                                    placeholder="<?=$this->translate('Ví dụ: example@email.com')?>"
                                    value="<?=$user->adm_email ?? ''?>">
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-12">
                            <div class="input-group input-group-static">
                                <label>
                                    <?= $this->translate('Địa chỉ') ?>
                                </label>
                                <input type="text" class="form-control" id="address" name="address"
                                    placeholder="<?=
                                        $this->translate('Ví dụ: 27 đường số 9, phường 16, quận Gò vấp, TPHCM')
                                    ?>"
                                    value="<?=$user->adm_address ?? ''?>">
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-md-6">
                            <div class="row">
                                <label class="form-label mb-2">
                                    <?= $this->translate('Số điện thoại') ?>
                                </label>
                                <div class="col-7">
                                    <select class="form-control" name="phone_code" id="phone_code" 
                                        data-value="<?=$user->adm_phone_code ?? '';?>">
                                    </select>
                                </div>
                                <div class="col-5">
                                    <div class="input-group input-group-static">
                                        <label class="form-label mb-2">&nbsp;</label>
                                        <input type="text" class="form-control" id="phone" name="phone" 
                                            placeholder="<?=$this->translate('Ví dụ: 0963123456')?>" 
                                            value="<?=$user->adm_phone ?? ''?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">
                                <?= $this->translate('Nhóm tài khoản') ?>
                            </label>
                            <?php
                            $select = new Element\Select('group_code');
                            $select->setAttributes([
                                'class' => 'form-control choices ps-2',
                                'id' => 'group_code',
                            ]);
                            $select->setValueOptions([
                                Admin::GROUP_MANAGER => $this->translate('Quản lý'),
                                Admin::GROUP_SUPPER_ADMIN => $this->translate('Super admin'),
                                Admin::GROUP_STAFF => $this->translate('Nhân viên'),
                                Admin::GROUP_TESTER => $this->translate('Tester'),
                            ]);
                            $select->setValue(htmlspecialchars($user->adm_groupcode ?? Admin::GROUP_STAFF));
                            echo $this->formSelect($select);
                            ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mt-4" id="password">
                <div class="card-header">
                    <h5>
                        <?= $this->translate('Mật khẩu') ?>
                    </h5>
                </div>
                <div class="card-body pt-0">
                    <div class="input-group input-group-outline my-4">
                        <label class="form-label">
                            <?= $this->translate('Mật khẩu') ?>
                        </label>
                        <input type="password" name="new_password" id="new_password" class="form-control" autocomplete="off">
                        <a href="javascript:;" class="position-absolute top-10px end-1 visible-icon show-pass" id="show-new-pass">
                            <i class="material-icons" aria-hidden="true">
                                visibility
                            </i>
                        </a>
                    </div>
                    <div class="input-group input-group-outline">
                        <label class="form-label">
                            <?= $this->translate('Xác nhận mật khẩu') ?>
                        </label>
                        <input type="password" name="confirm_new_password" id="confirm_new_password" class="form-control" autocomplete="off">
                        <a href="javascript:;" class="position-absolute top-10px end-1 visible-icon show-pass" id="confirm-new-pass">
                            <i class="material-icons" aria-hidden="true">
                                visibility
                            </i>
                        </a>
                    </div>
                    <h5 class="mt-5"><?= $this->translate('Yêu cầu mật khẩu')?></h5>
                    <p class="text-muted mb-2">
                        <?= $this->translate('Vui lòng làm theo hướng dẫn này để có mật khẩu mạnh:')?>
                    </p>
                    <ul class="text-muted ps-4 mb-0 float-start">
                        <li>
                            <span class="text-sm"><?= $this->translate('Phải bao gồm chữ cái in hoa, chữ thường, số, và ký tự đặc biệt.')?></span>
                        </li>
                        <li>
                            <span class="text-sm"><?= $this->translate('Độ dài phải từ 6 đến 50 ký tự.')?></span>
                        </li>
                        <li>
                            <span class="text-sm"><?= $this->translate('Thay đổi thường xuyên')?></span>
                        </li>
                    </ul>
                </div>
            </div>

        </form>
    </div>
</div>