<?php
use Laminas\Form\Element;

$this->headTitle($pageTitle);

$this->menuLeft()->setActiveItemId($activeItemId);
$this->bootstrapToolbar([
    $this->toolbarClose(
        $this->zfUrl(null, [], ['useOldQuery' => true])
    )
]);

$this->pageBreadcrumbs()->setItems([
    $this->translate('Trang chủ') => $this->zfUrl('home'),
    $pageTitle => $this->zfUrl($routeName),
]);

$pubRes = $this->zfResource();
$this->lazyAsset()->addItems([
    'js' => [
        21 => $pubRes->files('plugins/quill.min.js', 'js', false),
        22 => $pubRes->files('plugins/dropzone.min.js', 'js', false),
        23 => $pubRes->files('plugins/multistep-form.js', 'js', false),
    ],
]);

$this->headScriptAction(null, [], [
    'action' => 'add',
    'controller' => 'index',
    'module' => 'project'
]);
?>
<div class="row">
    <div class="col-12 m-auto">
        <div class="card">
            <div class="card-header pb-0 position-relative z-index-2">
                <div class="mb-3">
                    <h5 class="mb-0"><?= $this->translate($pageTitle)?></h5>
                </div>
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <div class="multisteps-form__progress">
                        <a class="multisteps-form__progress-btn btnDefault js-active" href="javascript:void(0);"
                            title="<?= $this->translate('Thông tin cơ bản')?>">
                            <span>1. <?= $this->translate('Thông tin cơ bản')?></span>
                        </a>
                        <a class="multisteps-form__progress-btn btnDefault" href="javascript:void(0);" title="Hình ảnh">
                            2. <?= $this->translate('Hình ảnh')?>
                        </a>
                        <a class="multisteps-form__progress-btn btnDefault" href="javascript:void(0);" title="SEO">
                            3. <?= $this->translate('SEO')?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form class="multisteps-form__form" method="POST" id="adminForm">
                    <div class="multisteps-form__panel pt-3 border-radius-xl bg-white js-active"
                        data-animation="FadeIn">
                        <h5 class="font-weight-bolder"><?= $this->translate('Thông tin cơ bản')?></h5>
                        <div class="multisteps-form__content">
                            <div class="row mt-3">
                                <div class="col-12 col-sm-6 mt-3">
                                    <div class="input-group input-group-dynamic">
                                        <label for="name" class="form-label">
                                            <?= $this->translate('Tên dự án')?>
                                        </label>
                                        <input class="multisteps-form__input form-control" type="text" 
                                            name="name" id="name"
                                            value="<?= $postData['name'] ?? ''; ?>"
                                            maxlength="512"/>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 mt-3">
                                    <div class="input-group input-group-dynamic">
                                        <label for="location" class="form-label">
                                            <?= $this->translate('Địa điểm')?>
                                        </label>
                                        <input class="multisteps-form__input form-control" type="text" 
                                            name="location" id="location"
                                            value="<?= $postData['location'] ?? ''; ?>"
                                            maxlength="255"/>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class=" col-12 col-sm-6 mt-3">
                                    <div class="input-group input-group-dynamic">
                                        <label for="assigned_to" class="form-label">
                                            <?= $this->translate('Người phụ trách')?>
                                        </label>
                                        <input class="multisteps-form__input form-control" type="text" 
                                            name="assigned_to" id="assigned_to"
                                            value="<?= $postData['assigned_to'] ?? ''; ?>"
                                            maxlength="50"/>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 ms-sm-auto mt-sm-0 mt-3 d-flex align-items-center">
                                    <label for="status" class="form-check-label mb-0">
                                        <small>
                                            <?= $this->translate('Trạng thái')?>
                                        </small>
                                    </label>
                                    <div class="form-check form-switch ms-2 my-auto">
                                        <input class="form-check-input" type="checkbox" id="status" name="status"
                                            <?= !empty($postData['status']) ? 'checked' : ''; ?>>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12 col-sm-6 mt-3">
                                    <label class="form-control ms-0">
                                        <?= $this->translate('Loại dự án')?>
                                    </label>
                                    <?php
                                        $select = new Element\Select('prc_id');
                                        $select->setAttributes([
                                            'class' => 'form-control choices',
                                            'id' => 'prc_id'
                                        ]);
                                        $select->setValueOptions(array_replace([
                                            '' => $this->translate('Vui lòng chọn')
                                        ], $prCates));
                                        $select->setValue($postData['prc_id'] ?? '');
                                        echo $this->formSelect($select);
                                    ?>
                                </div>
                                <div class="col-12 col-sm-6 mt-3">
                                    <label class="form-control ms-0">
                                        <?= $this->translate('Loại dịch vụ')?>
                                    </label>
                                    <?php
                                        $select = new Element\Select('sv_id');
                                        $select->setAttributes([
                                            'class' => 'form-control choices',
                                            'id' => 'sv_id'
                                        ]);
                                        $select->setValueOptions(array_replace([
                                            '' => $this->translate('Vui lòng chọn')
                                        ], $prServices));
                                        $select->setValue($postData['sv_id'] ?? '');
                                        echo $this->formSelect($select);
                                    ?>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-12">
                                    <label class="mt-4"><?= $this->translate('Mô tả')?></label>
                                    <div id="description" style="height:300px">
                                        <?= $postData['description'] ?? ''?>
                                    </div>
                                </div>
                            </div>
                            <div class="button-row d-flex mt-4">
                                <a class="btn bg-gradient-dark ms-auto mb-0 js-btn-next" id="btnNextStep2"
                                    title="<?= $this->translate('Tiếp theo')?>">
                                    <?= $this->translate('Tiếp theo')?>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="multisteps-form__panel pt-3 border-radius-xl bg-white"
                        data-animation="FadeIn">
                        <h5 class="font-weight-bolder"><?= $this->translate('Hình ảnh')?></h5>
                        <div class="multisteps-form__content">
                            <div class="row mt-3">
                                <div class="col-12">
                                    <label class="form-control mb-0"><?= $this->translate('Thumbnail')?></label>
                                    <div action="<?= $this->zfUrl('file-upload', ['action' => 'upload'], ['query' => [
                                        'path' => FOLDER_IMAGE_PRODUCT
                                    ]]); ?>" 
                                        class="form-control border dropzone"
                                        id="thumbnail" style="height:200px"></div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    <label class="form-control mb-0"><?= $this->translate('Danh sách hình ảnh')?></label>
                                    <div action="<?= $this->zfUrl('file-upload', ['action' => 'upload'], ['query' => [
                                        'path' => FOLDER_IMAGE_PRODUCT
                                    ]]); ?>"
                                        class="form-control border dropzone"
                                        id="jsonImage" style="height:200px"></div>
                                </div>
                            </div>
                            <div class="button-row d-flex mt-4">
                                <button class="btn bg-gradient-light mb-0 js-btn-prev" type="button"
                                    title="Prev"><?= $this->translate('Quay lại')?></button>
                                <a class="btn bg-gradient-dark ms-auto mb-0 js-btn-next" id="btnNextStep3"
                                    title="<?= $this->translate('Tiếp theo')?>">
                                    <?= $this->translate('Tiếp theo')?>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="multisteps-form__panel pt-3 border-radius-xl bg-white"
                        data-animation="FadeIn">
                        <h5 class="font-weight-bolder"><?= $this->translate('SEO')?></h5>
                        <div class="multisteps-form__content">
                            <div class="row mt-3">
                                <div class="col-12 mt-3">
                                    <div class="input-group input-group-dynamic">
                                        <label for="meta_title" class="form-label">
                                            <?= $this->translate('Meta title')?>
                                        </label>
                                        <input class="multisteps-form__input form-control" type="text" 
                                            name="meta_title" id="meta_title"
                                            value="<?= $postData['meta_title'] ?? ''; ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <label class="mt-4 form-label"><?= $this->translate('Meta keyword')?></label>
                                    <input class="multisteps-form__input form-control" type="text" 
                                        name="meta_keyword" id="meta_keyword"
                                        value="<?= $postData['meta_keyword'] ?? ''; ?>"/>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-12">
                                    <label class="mt-4"><?= $this->translate('Mô tả')?></label>
                                    <div id="meta_desc" style="height:300px">
                                        <?= $postData['meta_desc'] ?? ''?>
                                    </div>
                                </div>
                            </div>
                            <div class="button-row d-flex mt-4">
                                <button class="btn bg-gradient-light mb-0 js-btn-prev" type="button"
                                    title="Prev"><?= $this->translate('Quay lại')?></button>
                                <a class="btn bg-gradient-dark ms-auto mb-0" id="btnSubmit"
                                    href="javascript:void(0);" title="<?= $this->translate('Lưu')?>">
                                    <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                                    <span class="txt-btn"><?= $this->translate('Lưu') ?></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>