<?php
use Laminas\Form\Element;
use Models\Entities\Project;
use Models\Utilities\ImageUrl;
$this->headTitle($pageTitle);
$this->menuLeft()->setActiveItemId('project_list');
$this->bootstrapToolbar([
    $this->toolbarInsert($this->zfUrl($routeName, ['action'=>'add'])),
    $this->toolbarDelete($this->zfUrl($routeName, ['action'=>'delete'])),
]);

$this->pageBreadcrumbs()->setItems([
    $this->translate('Trang chủ') => $this->zfUrl('home'),
    $pageTitle => $this->zfUrl($routeName),
]);

$this->headScriptAction(null, [
    '__token__' => $token = $this->zfCsrfToken()->generateCsrfToken(
        [Project::FOLDER_TOKEN, microtime(true), rand(100, 999999)],
        Project::FOLDER_TOKEN
    ),
    '__error_info__' => $this->translate(ZF_MSG_WENT_WRONG),
], [
    'action' => 'index',
    'controller' => 'index',
    'module' => 'project'
]);
$this->headStyleAction(null, [], [
    'action' => 'index', 'controller' => 'index', 'module' => 'project'
]);
?>
<div class="row">
    <div class="col-12">
        <form id="adminForm" method="get" enctype="application/x-www-form-urlencoded">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-lg-flex">
                        <div>
                            <h5 class="mb-0"><?= $pageTitle?></h5>
                        </div>
                        <div class="ms-auto my-auto mt-lg-0 mt-2">
                            <div class="ms-auto my-auto">
                                <button class="btn btn-icon btn-outline-primary btn-sm mb-0" type="button">
                                    <i class="material-icons text-xs position-relative">archive</i>
                                    <?= $this->translate('Xuất excel')?>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="input-group input-group-outline mt-3">
                                <label class="form-label">
                                    <?= $this->translate('Tìm kiếm')?>
                                </label>
                                <input type="text" name="keyword" class="form-control" autocomplete="off"
                                    value="<?= $getData['keyword'] ?? ''?>">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="select mt-3">
                            <?php
                                $select = new Element\Select('prc_id');
                                $select->setAttributes([
                                    'class' => 'form-control px-3',
                                    'id' => 'prc_id'
                                ]);
                                $select->setValueOptions(array_replace([
                                    '' => $this->translate('Loại dự án')
                                ], $prCates));
                                $select->setValue($getData['prc_id'] ?? '');
                                echo $this->formSelect($select);
                            ?>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="select mt-3">
                            <?php
                                $select = new Element\Select('sv_id');
                                $select->setAttributes([
                                    'class' => 'form-control px-3',
                                    'id' => 'sv_id'
                                ]);
                                $select->setValueOptions(array_replace([
                                    '' => $this->translate('Loại dịch vụ')
                                ], $prServices));
                                $select->setValue($getData['sv_id'] ?? '');
                                echo $this->formSelect($select);
                            ?>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <button class="btn btn-icon bg-gradient-primary btn-md mt-3 mb-0 px-3" type="submit">
                                <i class="material-icons text-md position-relative">search</i>
                                <?= $this->translate('Tìm kiếm');?>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body px-0 pb-0">
                    <div class="d-lg-flex ps-4">
                        <p class="text-sm mb-0">
                        <?= str_replace(
                            ['{current}', '{total}'],
                            [
                                !empty($paginator) ? $paginator?->getCurrentItemCount() : 0, 
                                $totalItem = !empty($paginator) ? $paginator?->getTotalItemCount() : 0
                            ],
                            $this->translate('Hiển thị {current} trên {total} entries')
                        );?>
                        </p>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="w-2 text-center fs-6">
                                        <?= $this->manageCheckboxAll();?>
                                    </th>
                                    <th class="text-dark text-xs text-secondary text-uppercase opacity-7">
                                        <?= $this->translate('Hình ảnh')?>
                                    </th>
                                    <th class="text-dark text-xs text-center text-secondary text-uppercase opacity-7">
                                        <?= $this->translate('Tên')?>
                                    </th>
                                    <th class="text-dark text-xs text-center text-secondary text-uppercase opacity-7">
                                        <?= $this->translate('Trạng thái')?>
                                    </th>
                                    <th class="text-dark text-xs text-center text-secondary text-uppercase opacity-7">
                                        <?= $this->translate('Tác vụ')?>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php 
                                if ($totalItem > 0):
                                    foreach ($paginator as $item): 
                                    $id = $item->pr_id ?? 0;
                                    ?><tr>
                                        <td class="text-center fs-6">
                                            <?= $this->manageCheckbox($id ?? 0)?>
                                        </td>
                                        <td>
                                            <div class="d-flex px-2 py-1">
                                                <div>
                                                    <?= ImageUrl::generateImageOrigin(
                                                        $item->pr_thumbnail, 
                                                        Project::PROJECT_THUMBNAIL_SIZES,
                                                        $item->pr_name,
                                                        Project::FOLDER_IMAGE,
                                                        'avatar-sm me-3'
                                                    );?>
                                                </div>
                                            </div>
                                        </td>
                                        <td><?= $item->pr_name ?? '';?></td>
                                        <td class="font-weight-normal">
                                            <div class="d-flex align-items-center justify-content-center"><?php
                                                echo $this->manageChangeStatus($this->zfUrl($routeName, [
                                                    'action'=>'change-status', 
                                                    'id'=> $id
                                                ]),
                                                    $item->pr_status ?? 0, ['data-token' => $token]
                                                );
                                                ?>
                                                <span><?= $item->pr_status 
                                                    ? $this->translate('Kích hoạt')
                                                    : $this->translate('Chưa kích hoạt')
                                                ?></span>
                                            </div>
                                        </td>
                                        <td class="text-sm text-center"><?php
                                            echo  $this->manageUpdate(
                                                $this->zfUrl($routeName, [
                                                    'action'=>'edit', 
                                                    'id'=> $id,
                                                ])
                                            );
                                            echo  $this->manageDelete($this->zfUrl($routeName, 
                                                ['action'=>'delete', 'id'=> $id])
                                            );
                                        ?>
                                        </td>
                                    </tr>
                                <?php endforeach; 
                                else: ?>
                                    <td class="text-center fs-7 text-danger" colspan="100">
                                        <?= $this->translate(ZF_MSG_DATA_NOT_EXISTS); ?>
                                    </td>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            
                <?php if ($totalItem > 0) : ?>
                    <div class="card-footer">
                        <?= $this->paginationControl(
                            $paginator, 'Sliding',
                            'application/partial/paginator', 
                            ['route' => $routeName]
                        );?>
                    </div>
                <?php endif; ?>
            </div>
        </form>
    </div>
</div>